<div class="in_con_opt_w popover" style="top:38px;right:7px;max-width:140px;">
	<div class="in_con_opt_w_inner" style="position:relative;width:100%;">
		<div class="arrow-up" style="position:absolute;top:-12px;right:1px;border-bottom:10px solid #FFFFFF"></div>
			<label class="in_con_w_opt_it" for="upload-evt-pic" style="display:block;" >
				<form method="POST" class="hdn-form" enctype="multipart/form-data">
				<input id="upload-evt-pic" class="upload-evt-pic hdn-input"  type="file" name="picture-label" title="Add photo to this event collection">
				</form>
				Upload Photo
			</label>
			<?php if($deletable) :?>
				<div class="in_con_w_opt_it remove-evt-pht">Delete Photo</div>
			<?php endif; ?>
	</div>
</div>