<div class="in_con_opt_w fri-oper popover" style="top:37px;right:7px;height:130px;width:66%;"> <!---don't forget to add popover after you've done-->
	<div class="in_con_opt_w_inner" style="position:relative;width:100%;height:100%;">
		<div class="arrow-up" style="position:absolute;top:-12px;right:5px;border-bottom:10px solid #FFFFFF"></div>
		<div class="inner-w" style="height:100%;position:relative;overflow:hidden;width:100%">
			<div class="main" style="position:absolute;width:100%;left:0px;background:#fff;">
				<div class="in_con_w_opt_it add-interest-group" style="cursor:default">Interest Group<img src="<?php echo IMGDIR ?>right_nxt.png" style="float:right;margin-top:4px" height="12" width="12"></div>
				<div class="in_con_w_opt_it view-connection">Connections<img src="<?php echo IMGDIR ?>right_nxt.png" style="float:right;margin-top:4px" height="12" width="12"></div>
				<div class="in_con_w_opt_it individual-contact">Message</div>
			</div>
			
			<!--starts int-group-->
			<div class="sub int-group child-scrollable hdn"  style="position:absolute;right:-100%;width:100%;background:#fff;">
				<div class="back-to-main" style="cursor:default;padding:10px;text-align:center;border-bottom:1px solid #f0f0f0;"><img src="<?php echo IMGDIR ?>left_nxt.png" style="float:left;margin-top:4px;margin-right:-12px;" height="12" width="12">Interest Group</div>
				<div style="max-height:130px;overflow:scroll">
					<?php if($rows !== false && sizeof($rows) > 0): ?>
					<?php foreach($rows as $row): ?>
						<?php  
							$hash = $in->isUserInInterest($_SESSION['id'],$user_to, $row['id']);
							if($hash !== false): 
						?>
							<div  class="in_con_border_top" style="padding:6px 10px;cursor:default;" data-key="<?php echo $row['id'] ?>" data-hash="<?php echo $hash ?>" title="In your <?php echo htmlentities($row['name']); ?> interest group">
								<img class="label-image" src="<?php echo $row['picture_url']; ?>" />
								<div class="inline-blk txt_ofl red-act" style="width:95px;margin-top:3px;font-size:13px;"><?php echo $row['name'] ?></div>
								<img class="remove-from-interest pointer animate-opacity" src="<?php echo IMGDIR ?>minus_icon.png" title="Remove from interest group" height="16" wdith="16" style="float:right;margin-top:8px;" />
							</div>
						<?php else: ?>
							<?php
								$sent =	$interest_request->isRequestAlreadySentForInterestId($_SESSION['id'],$user_to, $row['id']);
								if($sent): 
							?>
								<div  class="in_con_border_top" style="padding:6px 10px;cursor:default;" data-key="<?php echo $row['id'] ?>">
							<?php else:?>
								<div  class="in_con_w_opt_it in_con_border_top selectable" title="Connect to my <?php echo $row['name'] ?> interest group" style="padding:6px 10px;" data-key="<?php echo $row['id'] ?>">
							<?php endif; ?>	<!--ends first sent if-->
								<img class="label-image" src="<?php echo $row['picture_url']; ?>" />
								<div class="inline-blk txt_ofl" style="width:95px;margin-top:3px;font-size:13px;"><?php echo $row['name'] ?></div>
							<?php if($sent): ?>
								<img src="<?php echo IMGDIR ?>plane_sent_icon.png" class="request-sent"  title="Request Sent"/>
							<?php endif; ?><!--ends second sent if-->
								</div>
						<?php endif; ?>
					<?php  endforeach;?>
					<?php endif; ?>
				</div> <!--ends max-height -->

				<div  class="right-align" style="border-top:1px solid #f0f0f0;padding:6px;">
					<div class="inline-blk action-button center-align request un-requestable">Request</div>
				</div>
			</div> <!-- ends int-group-->
			
			<!--starts collection group-->
			<div class="sub connection-group child-scrollable hdn"  style="position:absolute;right:-100%;width:100%;background:#fff;">
				<div class="back-to-main" style="cursor:default;padding:10px;text-align:center"><img src="<?php echo IMGDIR ?>left_nxt.png" style="float:left;margin-top:4px;margin-right:-12px;" height="12" width="12">Connections</div>
				<div style="max-height:130px;overflow:scroll">
		
			
 				<?php if($rows_in !== false && sizeof($rows_in) > 0): ?>
					<?php foreach($rows_in as $row): ?>
						<div class="in_con_border_top" style="padding:6px;cursor:default;" data-key="<?php echo $row['hash'] ?>" title="In <?php echo $row['firstname'] ?>'s <?php echo htmlentities($row['name']) ?> interest group">
							<img class="label-image" src="<?php echo $row['picture_url'] ?>">
							<div class="inline-blk txt_ofl red-act" style="width:95px;margin-top:3px;font-size:13px;"><?php echo htmlentities($row['name']); ?></div>
							<img class="leave-interest-group pointer animate-opacity" src="<?php echo IMGDIR ?>minus_icon.png" title="Leave this interest group" height="16" wdith="16" style="float:right;margin-top:8px;">
						</div>
					<?php endforeach; ?>
 				<?php endif ?>
 				</div>
				</div>
				
			</div><!--ends collection group-->
		
			
			
			
			
		</div><!--ends inner-w-->
	</div><!--ends in_con_opt_w_inner -->
</div><!--ends in_con_opt_w -->
