<div class="in_con_opt_w switcher popover" style="top: 37px; right: 10px; display: block;"> <!---don't forget to add popover after you've done-->
	<div class="in_con_opt_w_inner" style="position:relative;width:100%;">
		<div class="arrow-up" style="position:absolute;top:-12px;right:8px;border-bottom:10px solid #FFFFFF"></div>
		<div class="inner-w" style="position: relative; overflow: hidden; width: 100%;">
			<!--starts int-group-->
			<div class="sub" style="margin-top: 6px;">
				<div style="max-height:130px;overflow:scroll">
					<?php if($rows !== false && sizeof($rows) > 0): ?>
						<?php foreach($rows as $row): ?>
							<div class="in_con_w_opt_it" style="padding:6px 10px;cursor:default;" data-key="<?php echo $row['id'] ?>">
								<img class="label-image" src="<?php echo $row['picture_url']; ?>">
								<div class="inline-blk txt_ofl<?php echo ($active_key == $row['id'])?' red-act':'' ?>" style="width:95px;margin-top:3px;font-size:13px;"><?php echo $row['name'] ?></div>
							</div>

						<?php endforeach; ?>
					<?php endif; ?>	
				</div> <!--ends max-height -->
			</div> 
		</div>
	</div><!--ends inner-w-->
</div>