<div class="popover-dialog-wrapper popover" style="position:absolute;left:0px;z-index:1;width:80%" >
	<div style="position:relative;width:100%;" >
		<div class="arrow-up" style="position:absolute;top:-8px;left:16px"></div>
		<div class="popover-overlay" style="z-index:-1;position:absolute;top:0px;left:0px;width:100%;height:100%;background:#3A3A3A;opacity:0.8;border-radius:4px;">
		</div>
		<div class="popover-dialog-content" style="z-index:1;color:#fff;padding:10px;">
		</div>
	</div>
</div> 