	<div id="popup-dialog" class="dialog inline-blk popup-dialog">
		<div class="dialog-header">
			<div class="dialog-header-inner">
				<div class="inline-blk left-align dialog-header-left-item"><div class="bar-title vertical-center"></div></div>
			</div>
		</div>
		<div class="dialog-body">
			<div class="body-text">
			</div>
		</div>
		<div class="edit-dialog-footer dialog-footer">
			<div class="inline-blk cancel-button popup-button dismiss" style="margin-right:2px" ></div>
			<div class="inline-blk action-button popup-button hdn" style="margin:0px 10px 0px 0px" ></div>
		</div>
	</div>
