<!DOCTYPE>
			<html>
				<body>
					<div style="padding:8px;">
						<div style="background: #780000;
									background: -webkit-linear-gradient(#a13030, #780000);
									background: -o-linear-gradient(#a13030,#780000);
									background: -moz-linear-gradient(#a13030,#780000);
									background: linear-gradient(#a13030,#780000);box-shadow: 1px 1px 10px gray;
								  border-radius: 5px;
								  text-align: center;
								  padding: 6px 10px;
								  color: #fff;
								  font-size: 16px;
								  font-weight: bold;display:inline-block;">
								L'sere
						</div>
						<div style="margin-top:30px;">
							<div>
								<div >
								<div style="margin-bottom:20px;">
									<div style="font: 300 14px/18px 'Lucida Grande',Lucida Sans,Lucida Sans Unicode,sans-serif,Arial,Helvetica,Verdana,sans-serif;color: #333;">Dear <?php echo $firstname ?>,</div>
								</div>

								<div style="margin-bottom:20px;">
									<div style="font: 300 14px/18px 'Lucida Grande',Lucida Sans,Lucida Sans Unicode,sans-serif,Arial,Helvetica,Verdana,sans-serif; color: #333;">Reset password on Lsere.</div>
								</div>

								<div style="margin-bottom:10px;">
									<div style="font: 300 14px/18px 'Lucida Grande',Lucida Sans,Lucida Sans Unicode,sans-serif,Arial,Helvetica,Verdana,sans-serif; color: #333;line-height:2.0;">You recently requested a password reset for your account <a style="color:#000;font-weight:500;" href="$email"><?php echo $email; ?></a>. To reset your password, please click the link below.</div>
								</div>

								<div style="margin-bottom:30px;">
									<a href="<?php echo $reset_dir ?>" style="font: 300 14px/18px 'Lucida Grande',Lucida Sans,Lucida Sans Unicode,sans-serif,Arial,Helvetica,Verdana,sans-serif; color: #333;color:rgb(60, 169, 226);text-decoration:none;">Reset Password ></a>
								</div>

								<div>
									<div style="font: 300 14px/18px 'Lucida Grande',Lucida Sans,Lucida Sans Unicode,sans-serif,Arial,Helvetica,Verdana,sans-serif;line-height:2.0;">Best,<br>Lsere Team </div>
								</div>

								</div>
							</div>
						</div>
					</div>
				</body>
			</html>