<footer id="frag-footer">
		<div id="footer-item-wrapper">
			<span class="footer-item" ><a  class="plain-lk" href="<?php echo ROOTDIR; ?>about" >About</a></span>
			<span class="footer-item"><a  class="plain-lk" href="<?php echo ROOTDIR; ?>privacy" >Privacy</a></span>
			<span  class="footer-item"><a  class="plain-lk" href="<?php echo ROOTDIR; ?>terms" >Term</a></span>
		</div>
		© 2015 Higout	
</footer>