<?php include_once 'child/prepare_head.php'; ?>
<!DOCTYPE html>
<html>
	<head>
	<meta charset="utf-8">
	<title id="page-title" data-m="<?php echo $new_message_notification_num; ?>"  data-n="<?php echo $notification_number; ?>"  ><?php echo $title; ?></title>
	<link rel="shortcut icon" type="image/x-icon" href="<?php echo IMGDIR; ?>favicon.ico" />
	<link rel="stylesheet" type="text/css" href="<?php echo ROOTDIR; ?>css/core.css">
	<link rel="stylesheet" type="text/css" href="<?php echo ROOTDIR; ?>css/animate.css">
	<link rel="stylesheet" type="text/css" href="<?php echo ROOTDIR; ?>css/smoothness/jquery-ui.css">
	<script type="text/javascript" src="<?php echo ROOTDIR; ?>js/jquery.js"></script>
	<script type="text/javascript" src="<?php echo ROOTDIR; ?>js/jquery-ui.js"></script>
	<script type="text/javascript" src="<?php echo ROOTDIR; ?>js/glob.js"></script>
	<script type="text/javascript" src="<?php echo ROOTDIR; ?>js/core.js"></script>
	<script type="text/javascript" src="<?php echo ROOTDIR; ?>js/index.js"></script>
	

	<!--[if lt IE 9]>
	<script src="dist/html5shiv.js"></script>
	<![endif]-->
	</head>
	
	
	<body>
	<?php require_once 'child/loggedin_header.php'; ?>
			<div style="width:90%;margin:0px auto">
			<div style="float:right;width:60%;margin-top:-60px;margin-right: 50px;">
				<img src="<?php echo IMGDIR; ?>intro.png" style="width:100%;">
			</div>
			<div>
				<h2 style="font-size:30px;margin-top:80px;color:#333">Your interest matters.</h2>
				<div style="font-size:16px;padding-left:3px;">Moments, Events, Friends and More</div>
			</div>
		</div>
	</body>
</html>