<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>Higout</title>
		<link rel="shortcut icon" type="image/x-icon" href="<?php echo IMGDIR; ?>favicon.ico" />
		<link rel="stylesheet" type="text/css" href="<?php echo ROOTDIR; ?>css/core.css">
		<link rel="stylesheet" type="text/css" href="<?php echo ROOTDIR; ?>css/login.css">
		<link rel="stylesheet" type="text/css" href="<?php echo ROOTDIR; ?>css/privacy.css">

		<script type="text/javascript" src="<?php echo ROOTDIR; ?>js/jquery.js"></script>
		<script type="text/javascript" src="<?php echo ROOTDIR; ?>js/glob.js"></script>
		<script type="text/javascript" src="<?php echo ROOTDIR; ?>js/core.js"></script>
		
		<!--[if lt IE 9]>
		<script src="dist/html5shiv.js"></script>
		<![endif]-->
	</head>
	<body>
		<div id="login-header">
				<div id="login-header-inner">
					<div id="logo" class="left-bar inline-blk" style="margin-top:-2px;">
						<div><img src="<?php echo LOGO_URL; ?>" height="44" width="80"></div>
					</div>
					<div class="inline-blk right-bar">
						<a href="<?php echo ROOTDIR; ?>" class="plain-lk"><span id="prompt-sign-up-header-top" class="pointer"><img class="right-bar-item" src="<?php echo IMGDIR ?>lock.png"  title="login" />Log in</span></a>
					</div>
				</div>
			</div>
		<?php  include_once TEMPLATE_PATH_CHILD.'terms_body.phtml'; ?>	
	</body>
</html>