<?php include_once 'child/prepare_head.php'; ?>
<!DOCTYPE html>
<html>
	<head>
	<meta charset="utf-8" name=viewport content="width=device-width, initial-scale=1">
	<title id="page-title" data-m="<?php echo $new_message_notification_num; ?>"  data-n="<?php echo $notification_number; ?>"  ><?php echo $title; ?></title>
	<link rel="shortcut icon" type="image/x-icon" href="<?php echo IMGDIR; ?>favicon.ico" />
	<link rel="stylesheet" type="text/css" href="<?php echo ROOTDIR; ?>css/core.css">
	<link rel="stylesheet" type="text/css" href="<?php echo ROOTDIR; ?>css/m_core.css">

	<link rel="stylesheet" type="text/css" href="<?php echo ROOTDIR; ?>css/animate.css">
	<link rel="stylesheet" type="text/css" href="<?php echo ROOTDIR; ?>css/smoothness/jquery-ui.css">
	<link rel="stylesheet" type="text/css" href="<?php echo ROOTDIR; ?>css/profile.css">
	<link rel="stylesheet" type="text/css" href="<?php echo ROOTDIR; ?>css/m_index.css">
	<script type="text/javascript" src="<?php echo ROOTDIR; ?>js/jquery.js"></script>
	<script type="text/javascript" src="<?php echo ROOTDIR; ?>js/jquery-ui.js"></script>
	<script type="text/javascript" src="<?php echo ROOTDIR; ?>js/glob.js"></script>
	<script type="text/javascript" src="<?php echo ROOTDIR; ?>js/core.js"></script>
	<script type="text/javascript" src="<?php echo ROOTDIR; ?>js/index.js"></script>


	<!--[if lt IE 9]>
	<script src="dist/html5shiv.js"></script>
	<![endif]-->
	</head>
	
	
	<!--400.625px post wrapper.-->
	<body>
		<?php //require_once 'child/loggedin_header_m.php'; ?>
		<div id="index-global-container">
			<div class="inline-blk" style="width:100%;margin-top:26px;">
				<div id="index-news-feed" data-fetchable = "true" >
					<?php echo $feed_content; ?>	
				</div>
			</div>		
		
		</div>
	
		<?php include_once TEMPLATE_PATH_CHILD.'footer-overlay-element.phtml'; ?>
	
	</body>
</html>