<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>Password Reset</title>
		<link rel="shortcut icon" type="image/x-icon" href="<?php echo IMGDIR; ?>favicon.ico" />
		<link rel="stylesheet" type="text/css" href="<?php echo ROOTDIR; ?>css/core.css">
		<link rel="stylesheet" type="text/css" href="<?php echo ROOTDIR; ?>css/animate.css">
		<link rel="stylesheet" type="text/css" href="<?php echo ROOTDIR; ?>css/login.css">
		<link rel="stylesheet" type="text/css" href="<?php echo ROOTDIR; ?>css/password.css">
		<script type="text/javascript" src="<?php echo ROOTDIR; ?>js/jquery.js"></script>
		<script type="text/javascript" src="<?php echo ROOTDIR; ?>js/glob.js"></script>
		<script type="text/javascript" src="<?php echo ROOTDIR; ?>js/core.js"></script>
		<script type="text/javascript" src="<?php echo ROOTDIR; ?>js/login.js"></script>
		<script type="text/javascript" src="<?php echo ROOTDIR; ?>js/password.js"></script>

		<!--[if lt IE 9]>
		<script src="dist/html5shiv.js"></script>
		<![endif]-->
	</head>
	<body>
		<div id="login-header">
			<div id="login-header-inner">
				<div id="logo" class="gradient-red-background left-bar inline-blk">
				Higout
				</div>
				<div class="inline-blk right-bar">
					<a href="<?php echo ROOTDIR; ?>" class="plain-lk"><span id="prompt-sign-up-header-top" class="pointer"><img class="right-bar-item" src="<?php echo IMGDIR ?>lock.png"  title="login" />Log in</span></a>
				</div>
			</div>
		</div>
		
		<div id="reset-box" style="width:100%;text-align:center">
				<div class="light-gray-shadow dialog inline-blk" style="width:40%;margin-top:100px">
					<div class="dialog-header">
						<div class="dialog-header-inner">
							<div class="inline-blk left-align dialog-header-left-item">
								<div class="bar-title vertical-center">
									<?php if($resetable): ?>
										Reset your password
									<?php else: ?>
										Search your account
									<?php endif; ?>
								</div>
							</div>
						</div>
					</div>
					<?php if(!$resetable): ?>
						<div id="search-account" class="dialog-body" style="height:84px;">
							<div class="popover-throwable" style="margin:30px 14px 14px 16px;"><input type="text" style="width: 80%; padding: 4px;" class="text" placeholder="enter yoru email address"><button class="silver-button continue" style="margin-left:10px;padding:4px;">Continue</button></div>
						</div>
						<div id="reset-option" class="dialog-body hdn" style="height:84px;">
						
						</div>
						<div id="reset-sent" class="dialog-body hdn" style="height:84px;">
							<div style="margin:14px;">
								We have sent you a link to reset your password via email address<div class="target-address"></div>
							</div>
						</div>
					<?php else: ?>
						<div id="reset-password" class="dialog-body" style="height:100px;">
							<div class="popover-throwable" style="margin:16px 14px 14px 16px;"><input id="reset-password-input" type="password"  class="text" style="width: 80%; padding: 4px;" placeholder="enter your new password"></div>
							<div class="popover-throwable" style="margin:0px 14px 14px 16px;"><input id="reset-password-input-repeat" type="password"  class="text" style="width: 80%; padding: 4px;" placeholder="enter your new passowrd again"><button class="silver-button submit" style="margin-left:10px;padding:6px;" data-key="<?php echo $_GET['reset'] ?>" >Submit</button></div>
						</div>
						<div id="reset-password-succeed" class="dialog-body hdn" style="height:124px;">	

							<div style="margin:14px;"><div class="inline-blk"><img src="<?php echo IMGDIR ?>check_icon.png" style="height:20px;width:20px;margin-right:4px;"></div>
You have successfully reset your password <a class="plain-lk" href="<?php echo ROOTDIR; ?>login.php" style="color:#137CA0">Back to Login</a> </div>
						</div>
						
						
					<?php endif; ?>
				</div>
			</div>
		
		
	</body>
	
</html>