<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>Password Reset</title>
		<link rel="shortcut icon" type="image/x-icon" href="<?php echo ROOTDIR; ?>favicon.ico" />
		<link rel="stylesheet" type="text/css" href="<?php echo ROOTDIR; ?>css/core.css">
		<link rel="stylesheet" type="text/css" href="<?php echo ROOTDIR; ?>css/animate.css">
		<link rel="stylesheet" type="text/css" href="<?php echo ROOTDIR; ?>css/login.css">
		<link rel="stylesheet" type="text/css" href="<?php echo ROOTDIR; ?>css/password.css">
		<script type="text/javascript" src="<?php echo ROOTDIR; ?>js/jquery.js"></script>
		<script type="text/javascript" src="<?php echo ROOTDIR; ?>js/core.js"></script>
		<script type="text/javascript" src="<?php echo ROOTDIR; ?>js/login.js"></script>
		<script type="text/javascript" src="<?php echo ROOTDIR; ?>js/password.js"></script>

		<!--[if lt IE 9]>
		<script src="dist/html5shiv.js"></script>
		<![endif]-->
	</head>
	<body>
		<div id="login-header">
			<div id="login-header-inner">
				<div id="logo" class="gradient-red-background left-bar inline-blk">
				L'sere
				</div>
				<div class="inline-blk right-bar">
					<a href="<?php echo ROOTDIR; ?>login.php" class="dummy-lk"><span id="prompt-sign-up-header-top" class="pointer"><img class="right-bar-item" src="<?php echo IMGDIR ?>lock.png"  title="login" />Sign in</span></a>
				</div>
			</div>
		</div>
		
		<div id="reset-box" style="width:100%;text-align:center">
				<div class="light-gray-shadow dialog inline-blk" style="width:40%;margin-top:100px">
					<div class="dialog-header">
						<div class="dialog-header-inner">
							<div class="inline-blk left-align dialog-header-left-item"><div class="bar-title vertical-center">Search your account</div></div>
						</div>
					</div>
					<div id="search-account" class="dialog-body" style="height:84px;">
						<div class="popover-throwable" style="margin:30px 14px 14px 16px;"><input type="text" style="width: 80%; padding: 4px;" class="text" placeholder="enter yoru email address"><button class="silver-button continue" style="margin-left:10px;padding:4px;">Continue</button></div>
					</div>
					<div id="reset-option" class="dialog-body hdn" style="height:84px;">
						
					</div>
				</div>
			</div>
		
		
	</body>
	
</html>