<?php //include_once 'child/prepare_head.php'; ?>
<!DOCTYPE html>
<html>
	<head>	
		<meta charset="utf-8" name="viewport" content="width=device-width,initial-scale=1">
		<title id="page-title"  >Kesong Xie (@kesongxie) - Scenested</title>
		<link rel="stylesheet" type="text/css" href="<?php echo ROOTDIR; ?>css/core.css">
		<link rel="stylesheet" type="text/css" href="<?php echo ROOTDIR; ?>css/core.inc.css">
		<link rel="stylesheet" type="text/css" href="<?php echo ROOTDIR; ?>css/profile_content.css">
		<link rel="stylesheet" type="text/css" href="<?php echo ROOTDIR; ?>css/animate.css">
		<script type="text/javascript" src="<?php echo ROOTDIR; ?>js/jquery.js"></script>
		<script type="text/javascript" src="<?php echo ROOTDIR; ?>js/touch-punch-min.js"></script>
		<script type="text/javascript" src="<?php echo ROOTDIR; ?>js/jquery-ui.js"></script>
		<script type="text/javascript" src="<?php echo ROOTDIR; ?>js/glob.js"></script>
		<script type="text/javascript" src="<?php echo ROOTDIR; ?>js/core.js"></script>
		<script type="text/javascript" src="<?php echo ROOTDIR; ?>js/core.inc.js"></script>
		<script type="text/javascript" src="<?php echo ROOTDIR; ?>js/profile.js"></script>
		<!--[if lt IE 9]>
		<script src="dist/html5shiv.js"></script>
		<![endif]-->
	</head>
	<body id="profile-whole-container">
		<div id="profile-body-whole-container">
			<div class="user-cover">
				<div class="inner">
					<img id="profile-cover" class="cover-image" src="<?php echo convertThumbPathToOriginPath($user_profile_cover_image) ?>">
					<img src="<?php echo IMGDIR; ?>setting_icon.png" style="position:absolute;right:12px;top:12px;" height="28" width="28">
				</div>
			</div>
			<div id="profile-main-content">
				<div id="profile-left-content-wrapper">
					<div id="profile-left-content-inner-wrapper" >
						<div style="padding:0px 10px;">
							<div id="profile-avator-wrapper" style="">
								<img id="profile-avator" src="<?php echo $user_profile_avator_image; ?>">
								<div id="avator-edit-profile">
									<div id="a-e-p-overlay"></div>
									<div id="a-e-p-edit">EDIT PROFILE</div>
								</div>
							
							</div>
				
							<div id="profile-statistic-wrapper" class="inline-blk">
								<div>
									<div class="statistic-block inline-blk pointer">
										
										<div class="profile-data"><?php echo $profile_scene_num; ?></div>
										<div class="profile-data-label" >Scenes</div>
									</div>
									<div class="statistic-block inline-blk pointer">
										
										<div class="profile-data">60</div>
										<div class="profile-data-label" >Followers</div>
									</div>
									<div class="statistic-block inline-blk pointer">
										
										<div class="profile-data">84</div>
										<div class="profile-data-label" >Following</div>
									</div>
								</div>
							
							
								
							</div>
							
							
						</div>
					
						
					
						<div id="profile-name-wrapper"  style="padding:0px 16px;">
							<div id="profile-name" class="txt-overflow" style="font-size:22px">kesongxie</div>
						</div>
						
						<div style="padding:0px 20px;margin-top:10px;" class="hdn">
								<button id="trigger-add-scene-button"  class="animated-button blue-action-button">FOLLOW</button>
								
								<div class="inline-blk hdn" style="margin-left:40px;">
									<img src="<?php echo IMGDIR ?>setting_icon.png" style="opacity: 0.6" height="24" width="24">
								</div>
							</div>
								
					
						
							<div id="profile-short-bio" class="profile-bio" style="padding:0px 16px;margin-top:20px;">
								<?php echo enRichText($bio); ?>
							</div>
						
							<div class="profile-bio hdn" style="margin-top:10px;">
								Stanford University
							</div>
						
							<div id="profile-scene-label-wrapper" class="" style="padding:0px 16px;margin-top:4px;">
								<div class="profile-bio" >
									<?php if($labels !== false): ?>
										<?php $label_num = sizeof($labels); $counter = 1; ?>
										<?php foreach($labels as $label): ?>
											<a href="#" class="plain-lk scene-label"><?php echo htmlentities($label['name']) ?></a><?php echo ($counter++ != $label_num)?',':'' ?>
										<?php endforeach; ?>
									<?php endif; ?>
								</div>
							</div>
						
						<div style="padding:0px 14px;margin-top:30px;" class="">
								<button id="trigger-add-scene-button"  class="animated-button blue-action-button" style="padding:0px 48px">FOLLOW</button>
								
								<div class="inline-blk hdn" style="margin-left:40px;">
									<img src="<?php echo IMGDIR ?>setting_icon.png" style="opacity: 0.6" height="24" width="24">
								</div>
							</div>
						
						
						
						
						
						
						<div id="profile-under-action" >
							<div class="inline-blk hdn"  style="margin:30px 0px;">
								<button id="trigger-add-scene-button" class="animated-button blue-action-button">SHARE SCENE</button>
							</div>
						
							<div class="inline-blk hdn"  style="margin:30px 0px;">
								<button id="follow-button" class="animated-button blue-action-button" style="padding:0px 30px;">&#9825 FOLLOW</button>
							</div>
						</div>
					</div>
				</div>
				<div id="profile-right-content-wrapper" style="margin-top:30px;">
					<?php echo $sceneBlock; ?>	
				
			
				</div>
			</div>
		</div>
		<?php include_once TEMPLATE_PATH_CHILD.'footer-overlay-element.phtml'; ?>
	</body>
</html>