<?php //include_once 'child/prepare_head.php'; ?>
<!DOCTYPE html>
<html>
	<head>	
		<meta charset="utf-8" name="viewport" content="width=device-width,initial-scale=1">
		<title id="page-title"  >Scenested</title>
		<link rel="stylesheet" type="text/css" href="<?php echo ROOTDIR; ?>css/core.css">
		<link rel="stylesheet" type="text/css" href="<?php echo ROOTDIR; ?>css/core.inc.css">
		<link rel="stylesheet" type="text/css" href="<?php echo ROOTDIR; ?>css/profile.css">
		<link rel="stylesheet" type="text/css" href="<?php echo ROOTDIR; ?>css/animate.css">
		<script type="text/javascript" src="<?php echo ROOTDIR; ?>js/jquery.js"></script>
		<script type="text/javascript" src="<?php echo ROOTDIR; ?>js/touch-punch-min.js"></script>
		<script type="text/javascript" src="<?php echo ROOTDIR; ?>js/jquery-ui.js"></script>
		<script type="text/javascript" src="<?php echo ROOTDIR; ?>js/glob.js"></script>
		<script type="text/javascript" src="<?php echo ROOTDIR; ?>js/core.js"></script>
		<script type="text/javascript" src="<?php echo ROOTDIR; ?>js/core.inc.js"></script>
		<script type="text/javascript" src="<?php echo ROOTDIR; ?>js/profile.js"></script>
		<!--[if lt IE 9]>
		<script src="dist/html5shiv.js"></script>
		<![endif]-->
	</head>
	<body id="profile-whole-container">
		<div id="gl-header">
			<div class="inner">
				<div id="gl-search-bar-wrapper">
					<div class="inner">
						<input id="gl-search-input" type="text" placeholder="Search">
						<button id="gl-search-button"></button>
					</div>
				</div>
			</div>	
		</div>
		
		<div id="profile-body-whole-container">
			<div class="user-cover">
				<div class="inner">
					<img id="profile-cover" class="cover-image" src="<?php echo convertThumbPathToOriginPath($user_profile_cover_image) ?>">
				</div>
			</div>
			<div id="profile-main-content">
				<div id="profile-left-content-wrapper">
					<div id="profile-left-content-inner-wrapper" >
						<div id="profile-avator-wrapper">
							<img id="profile-avator" src="<?php echo convertThumbPathToOriginPath($user_profile_avator_image) ?>">
							<div id="avator-edit-profile">
								<div id="a-e-p-overlay"></div>
								<div id="a-e-p-edit">EDIT PROFILE</div>
							</div>
						</div>
				
						<div id="profile-name-wrapper">
							<div id="profile-name" class="txt-overflow">Kesong Xie</div>
						</div>
					
						<div id="profile-statistic-wrapper">
								<div class="statistic-block inline-blk pointer">
									<div class="profile-data-label" >Scenes</div>
									<div class="profile-data">12</div>
								</div>
								<div class="statistic-block inline-blk pointer">
									<div class="profile-data-label" >Followers</div>
									<div class="profile-data">60</div>
								</div>
								<div class="statistic-block inline-blk pointer">
									<div class="profile-data-label" >Following</div>
									<div class="profile-data">84</div>
								</div>
							</div>
					
						<div id="profile-short-bio" class="profile-bio">
							<?php echo htmlentities($bio); ?>
						</div>
						<div id="profile-scene-label-wrapper"  style="margin-top:2px;">
							<div class="profile-bio" >
								<?php if($labels !== false): ?>
									<?php $label_num = sizeof($labels); $counter = 1; ?>
									<?php foreach($labels as $label): ?>
										<a href="#" class="plain-lk scene-label"><?php echo htmlentities($label['name']) ?></a><?php echo ($counter++ != $label_num)?',':'' ?>
									<?php endforeach; ?>
								<?php endif; ?>
							</div>
						</div>
	
						<div id="profile-follow">
							<div class="inline-blk"  style="margin:30px 0px;">
								<button id="add-scene-button" class="animated-button blue-action-button">ADD SCENE</button>
							</div>
						
							<div class="inline-blk hdn"  style="margin:30px 0px;">
								<button id="follow-button" class="animated-button blue-action-button" style="padding:0px 30px;">&#9825 FOLLOW</button>
							</div>
						</div>
					</div>
				</div>
				<div id="profile-right-content-wrapper">
					<div class="post">
						<div class="post-top">
							<div class="inline-blk post-tag-date">
								<div class="date">
									<div><span class="day">03</span><span class="mon">Nov</span></div>
									<div class="year" >2014</div>
								</div>
							</div>
							<img class="post-avator inline-blk" src="<?php echo DUMMY_MEDIA ?>avator.jpg">
							<div class="post-user-info inline-blk">
								<div class="post-head-line">
									<span class="post-user-name pointer">Kesong Xie</span>
									<span class="head-additional-info"><a href="#" title="link to people with similar interest in your near location" class="plain-lk"><span class="scene-label">Tennis</span></a> - 2h</span>
								</div>
								<div class="post-content-text">
									<span>How does it feel for this years' <a href="#"  class="plain-lk"><span class="hash-tag">#USOpen</span></a> I think <span class="hash-tag">@RogerFederer</span> is going to fight into the final.</span>
								</div>
							</div>
						</div>
						<div class="post-mid">
							<div class="inline-blk post-image">
								<div class="post-image-one-picture">
									<img class="post-attached-img" src="<?php echo DUMMY_MEDIA?>IMG_5101.jpg">
								</div>
							</div>
						</div>
						<div class="post-bottom">
							<div class="post-user-interact" style="text-align:left">
								<div class="post-action-label inline-blk toggle-comment pointer" >
									<img class="post-operation-icon" src="<?php echo IMGDIR ?>ci.png" title="Comment" height="16" width="16">
									<div class="cmt-num action-num">0</div>
								</div>
								<div class="post-action-label inline-blk">
									<img class="post-operation-icon undo-favor-activity" src="<?php echo IMGDIR ?>like_action.png" title="Undo Favor" height="17" width="19">
									<div class="favor-num action-num">3</div>
								</div>
								<div class="post-action-label inline-blk pointer" style="float:right;" >
									<img class="post-operation-icon pointer" src="<?php echo IMGDIR ?>dot_icon.png" title="More" height="24" width="24" style="margin-top:-3px;">
								</div>
							</div>	
						</div>
					</div>
					<div class="post">
						<div class="post-top">
							<div class="inline-blk post-tag-date">
								<div class="date">
									<div><span class="day">02</span><span class="mon">May</span></div>
									<div class="year" >2015</div>
								</div>
							</div>
							<img class="post-avator inline-blk" src="<?php echo DUMMY_MEDIA ?>avator.jpg">
							<div class="post-user-info inline-blk">
								<div class="post-head-line">
									<span class="post-user-name pointer">Kesong Xie</span>
									<span class="head-additional-info"><a href="#" title="link to people with similar interest in your near location" class="plain-lk"><span class="scene-label">Programming</span></a> - 2h</span>
								</div>
								<div class="post-content-text">
									<span>A guy like me who is so picky about how the work looks is probably not suitable to join a ' <a href="#"  class="plain-lk"><span class="hash-tag">#hackathon</span></a>, but it's a great experience, though.</span>
								</div>
							</div>
						</div>
						<div class="post-mid">
							<div class="inline-blk post-image">
								<div class="post-image-one-picture">
									<img class="post-attached-img" src="<?php echo DUMMY_MEDIA?>100_1288.jpg">
								</div>
							</div>
						</div>
						<div class="post-bottom">
							<div class="post-user-interact" style="text-align:left">
								<div class="post-action-label inline-blk toggle-comment pointer" >
									<img class="post-operation-icon" src="<?php echo IMGDIR ?>ci.png" title="Comment" height="16" width="16">
									<div class="cmt-num action-num">0</div>
								</div>
								<div class="post-action-label inline-blk">
									<img class="post-operation-icon undo-favor-activity" src="<?php echo IMGDIR ?>like_action.png" title="Undo Favor" height="17" width="19">
									<div class="favor-num action-num">3</div>
								</div>
								<div class="post-action-label inline-blk pointer" style="float:right;" >
									<img class="post-operation-icon pointer" src="<?php echo IMGDIR ?>dot_icon.png" title="More" height="24" width="24" style="margin-top:-3px;">
								</div>
							</div>	
						</div>
					</div>
				</div>
			</div>
		</div>
		<?php include_once TEMPLATE_PATH_CHILD.'footer-overlay-element.phtml'; ?>
	</body>
</html>