<!DOCTYPE>
<html>
	<body>
	<div style="padding:20px;">
		<div style="background: #780000;
					background: -webkit-linear-gradient(#a13030, #780000);
					background: -o-linear-gradient(#a13030,#780000);
					background: -moz-linear-gradient(#a13030,#780000);
					background: linear-gradient(#a13030,#780000);box-shadow: 1px 1px 10px gray;
				  border-radius: 5px;
				  text-align: center;
				  padding: 6px 10px;
				  color: #fff;
				  font-size: 18px;
				  font-weight: bold;display:inline-block;">
				L'sere
		</div>
		<div style="margin-top:30px;">
			<table>
				<tbody >
				<tr>
					<td style="font: 300 14px/18px 'Lucida Grande',Lucida Sans,Lucida Sans Unicode,sans-serif,Arial,Helvetica,Verdana,sans-serif;color: #333;">Dear Kesong Xie,</td>
				</tr>
				
				<tr>
					<td style="font: 300 14px/18px 'Lucida Grande',Lucida Sans,Lucida Sans Unicode,sans-serif,Arial,Helvetica,Verdana,sans-serif; color: #333;">Thank you for joining Lsere.</td>
				</tr>
				
				<tr>
					<td style="font: 300 14px/18px 'Lucida Grande',Lucida Sans,Lucida Sans Unicode,sans-serif,Arial,Helvetica,Verdana,sans-serif; color: #333;">You recently signed up on Lsere using <strong>kesong_xie@yahoo.com</strong>. To verify this email address, please click the link below and then you can sign in using this email adress and your password</td>
				</tr>
				
				<tr>
					<a><td style="font: 300 14px/18px 'Lucida Grande',Lucida Sans,Lucida Sans Unicode,sans-serif,Arial,Helvetica,Verdana,sans-serif; color: #333;color:rgb(60, 169, 226)">Verify now > </td></a>
				</tr>
				
				<tr>
					<td style="font: 300 14px/18px 'Lucida Grande',Lucida Sans,Lucida Sans Unicode,sans-serif,Arial,Helvetica,Verdana,sans-serif;">Lsere Team </td>
				</tr>
				
				</tbody>
			</table>
		</div>
	</div>
		
	</body>
</html>
