<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>Lsere</title>
		<link rel="shortcut icon" type="image/x-icon" href="<?php echo ROOTDIR; ?>favicon.ico" />
		<link rel="stylesheet" type="text/css" href="<?php echo ROOTDIR; ?>css/core.css">
		<link rel="stylesheet" type="text/css" href="<?php echo ROOTDIR; ?>css/animate.css">
		<link rel="stylesheet" type="text/css" href="<?php echo ROOTDIR; ?>css/search.css">
		<script type="text/javascript" src="<?php echo ROOTDIR; ?>js/jquery.js"></script>
		<script type="text/javascript" src="<?php echo ROOTDIR; ?>js/jquery-ui.js"></script>
		<script type="text/javascript" src="<?php echo ROOTDIR; ?>js/core.js"></script>
		<script type="text/javascript" src="<?php echo ROOTDIR; ?>js/search.js"></script>


		<!--[if lt IE 9]>
		<script src="dist/html5shiv.js"></script>
		<![endif]-->
	</head>
	<body>
	<?php require_once 'child/loggedin_header.php'; ?>
		<div id="profile-global-container">
			<div id="search-sider-bar-left" class="inline-blk"></div>
			
			<div id="search-sider-bar-right"  class="inline-blk">
					<div id="search-navigation-bar">
						<a href="<?php echo $BASE_PATH.'?k='.$_GET['k']; ?>"><div class="navi-item<?php echo ( (!isset($_GET['t']) || ($_GET['t']!='event' && $_GET['t']!='photo' && $_GET['t']!='post' ))?' active-navi':' deactive-navi'   ) ?>">People<div class="sub-text" style="left:15px;">events</div></div></a>
						<a href="<?php echo $BASE_PATH.'?k='.$_GET['k'].'&t=event'; ?>"><div class="navi-item<?php echo (isset($_GET['t']) && $_GET['t'] == 'event')?' active-navi':' deactive-navi' ?>" >Events<div class="sub-text" style="left:15px;">upcomings &amp; joined</div></div></a>
						<a href="<?php echo $BASE_PATH.'?k='.$_GET['k'].'&t=post'; ?>"><div class="navi-item<?php echo (isset($_GET['t']) && $_GET['t'] == 'post')?' active-navi':' deactive-navi' ?>" >Posts<div class="sub-text" style="left:15px;">blogged</div></div></a>
						<a href="<?php echo $BASE_PATH.'?k='.$_GET['k'].'&t=photo'; ?>"><div class="navi-item<?php echo (isset($_GET['t']) && $_GET['t'] == 'photo')?' active-navi':' deactive-navi' ?>" >Photos<div class="sub-text" style="left:15px;">shared</div></div></a>
					
					</div>
					<div>
						<?php echo $search_result_main_block; ?>
					
					</div>
			</div>
		</div>
	
	<?php include_once 'chat.php'; ?>
	<?php include_once TEMPLATE_PATH_CHILD.'footer-overlay-element.phtml'; ?>

	
	</body>
</html>	
