<!DOCTYPE html>
<html>
	<?php include_once 'child/prepare_head.php'; ?>
	<head>
		<meta charset="utf-8">
		<title id="page-title" data-m="<?php echo $new_message_notification_num; ?>"  data-n="<?php echo $notification_number; ?>"  ><?php echo $title; ?></title>
		<link rel="shortcut icon" type="image/x-icon" href="<?php echo ROOTDIR; ?>favicon.ico" />
		<link rel="stylesheet" type="text/css" href="<?php echo ROOTDIR; ?>css/core.css">
		<link rel="stylesheet" type="text/css" href="<?php echo ROOTDIR; ?>css/animate.css">
		<link rel="stylesheet" type="text/css" href="<?php echo ROOTDIR; ?>css/search.css">
		<script type="text/javascript" src="<?php echo ROOTDIR; ?>js/jquery.js"></script>
		<script type="text/javascript" src="<?php echo ROOTDIR; ?>js/jquery-ui.js"></script>
		<script type="text/javascript" src="<?php echo ROOTDIR; ?>js/core.js"></script>
		<script type="text/javascript" src="<?php echo ROOTDIR; ?>js/search.js"></script>


		<!--[if lt IE 9]>
		<script src="dist/html5shiv.js"></script>
		<![endif]-->
	</head>
	<body onload="prepare();">
	<?php require_once 'child/loggedin_header.php'; ?>
		<div id="profile-global-container" class="side-bar">
			<div style="margin-top:14px;">
				<div id="search-sider-bar-left" class="inline-blk" style="margin-left:64px;">
					<?php if($similar_interest_block !== null):	?>
						<?php echo $similar_interest_block; ?>
					<?php endif; ?>
					<!-- 
<div style="margin-top:100px;">
						<?php require_once 'phtml/footer.phtml'; ?>
					</div>
 -->
				</div>
			
				<div id="search-sider-bar-right"  class="inline-blk">
					<div id="search-navigation-bar">
						<?php 
							if(isset($_GET['q'])){
								$title_url = $BASE_PATH.'?q='.$_GET['q'];
							}else if($_GET['r']){
								$title_url = $BASE_PATH.'?r='.$_GET['r'];
							}
						
						 ?>
					
						<a href="<?php echo $title_url ?>"><div class="navi-item<?php echo ( (!isset($_GET['t']) || ($_GET['t']!='event' && $_GET['t']!='photo' && $_GET['t']!='post' ))?' active-navi':' deactive-navi'   ) ?>">People<div class="sub-text" style="left:15px;">events</div></div></a>
						<a href="<?php echo $title_url ?>&t=event"><div class="navi-item<?php echo (isset($_GET['t']) && $_GET['t'] == 'event')?' active-navi':' deactive-navi' ?>" >Events<div class="sub-text" style="left:15px;">upcomings &amp; collected</div></div></a>
						<a href="<?php echo $title_url ?>&t=post"><div class="navi-item<?php echo (isset($_GET['t']) && $_GET['t'] == 'post')?' active-navi':' deactive-navi' ?>" >Moments<div class="sub-text" style="left:15px;">post</div></div></a>
						<a href="<?php echo $title_url ?>&t=photo"><div class="navi-item<?php echo (isset($_GET['t']) && $_GET['t'] == 'photo')?' active-navi':' deactive-navi' ?>" >Photos<div class="sub-text" style="left:15px;">shared</div></div></a>
					
					</div>
					<div>
						<?php echo $search_result_main_block; ?>
					
					</div>
			</div>
			</div>
	</div>	
	
	<?php include_once 'child/chat.php'; ?>
	<?php include_once TEMPLATE_PATH_CHILD.'footer-overlay-element.phtml'; ?>

	
	</body>
</html>	
