<div class="side-block-wrapper">
	<div class="title">
		<span class="title-text">Abouts</span>
		<?php if($user_id == $_SESSION['id']): ?>
			<div class="action inline-blk" style="position:relative;float:right;">
				<img class="side-blur-action show-edit pointer hdn act" src="<?php echo IMGDIR ?>add_icon.png" height="14" width="14" title="Edit something about you" style="margin-top:4px;">
				<img class="side-blur-action hide-edit pointer hdn" src="<?php echo IMGDIR ?>minus_icon.png" height="18" width="18" title="Cancel editting" style="margin-top:2px;">

				<div class="in_con_opt_w popover" style="top: 30px; right: -9px;width:160px;height:43px;">
					<div class="in_con_opt_w_inner" style="position:relative;width:100%;height:100%;">
						<div class="arrow-up" style="position:absolute;top:-12px;right:1px;border-bottom:10px solid #FFFFFF"></div>
						<div class="inner-w" style="height:100%;position:relative;overflow:hidden;width:100%">
							<div class="main" style="position: absolute; width: 100%; left: 0px; background: rgb(255, 255, 255);">
								<div class="in_con_w_opt_it update-education" style="cursor:default">Update Education<img src="<?php echo IMGDIR ?>right_nxt.png" style="float:right;margin-top:4px" height="12" width="12"></div>
							</div>
					
							<div class="sub educ hdn" style="position: absolute; right: -100%; width: 100%; background: rgb(255, 255, 255);">
								<div class="back-to-main" style="cursor:default;padding:10px;text-align:center;border-bottom:1px solid #f0f0f0""><img src="<?php echo IMGDIR ?>left_nxt.png" style="float:left;margin-top:4px;margin-right:2px;" height="12" width="12">Update Education</div>
								<div class="in_con_w_opt_it add-school" style="cursor:default"><div class="inline-blk" style="margin-right:6px;"><img src="<?php echo IMGDIR ?>hat.png" height="20" width="20"></div>School</div>
								<div class="in_con_w_opt_it add-study" style="cursor:default"><div class="inline-blk" style="margin-right:9px;opacity:0.5;padding-top:2px;"><img src="<?php echo IMGDIR ?>diploma_icon.png" height="16" width="16"></div>Study and Major</div>

							</div>
						</div>
				</div>
				</div>
			</div>
		<?php endif; ?>
	</div>
	<?php if($user_id == $_SESSION['id']): ?>
	<div class="side-block-edit-wrapper edu hdn">
		<div class="popover-throwable school-name-input-wrapper edit-input hdn" style="margin-bottom:10px;">
			<div style="width:100%;"><input type="text" class="fcy-txt" value="<?php echo $education['school_name']; ?>" placeholder="School name..." maxlength="100"></div>
			<div class="school-name-suggest hdn">
			</div>
		</div>
		
		<div class="popover-throwable major-name-input-wrapper edit-input hdn" >
			<div style="width:100%;"><input type="text" class="fcy-txt" value="<?php echo htmlentities($education['study']); ?>" placeholder="What do you study..." maxlength="100"></div>
			<div class="major-name-suggest hdn">
				
			</div>
		</div>
	</div>
	<?php endif; ?>
	
	
	<div class="side-block-main-wrapper front<?php echo ($education === false)?' hdn':' act' ?>">
		<div class="name plain-lk pointer" style="color:rgb(48, 51, 198)">
		<?php if($education !== false): ?>
			<?php echo $education['school_name']; ?>
		<?php endif; ?>	
		</div>
		<div class="major" style="font-size:12px;margin-top:2px;"><?php echo htmlentities($education['study']); ?></div>
	</div>	
	
		
	
	
	
	<div class="empty front<?php echo ($education !== false)?' hdn':' act' ?>" style="background:#fff;position:relative" >
	<?php if($user_id == $_SESSION['id']): ?>
		You haven't added something about you yet, <span id="show-favor-edit" class="plain-lk pointer" style="color:#062AA3">Let your friends know</span>
	<?php else:  ?>
		<?php echo $firstname ?> hasn't updated something about
	<?php endif; ?>
	</div>	
	
</div>


