<div id="chat-outer-wrapper" class="strech" >
	<div id="chat-side-content" style="position:relative;height:100%;width:100%;">
		<div id="chat-bar" style="height:100%;position:relative;">
			<div class="chat-header">
				<div class="title">
				<div class="inline-blk" style=" color: inherit;">Messages</div>
				<div id="chat-search" class="inline-blk" title="Search Contact">
					<img src="<?php echo IMGDIR; ?>search_icon.png" height="15px" width="15px">
				</div>
			</div>
			</div>
			<div class="chat-body" style="padding:0px 10px;position:relative;overflow:hidden;height:90%;">
					<?php echo $contact_block; ?>
				<div id="broken-connect-overlay" class="broken-connect<?php echo (isset($_SESSION['id']))?' hdn':'' ?>">
				</div>	
			</div>
			<div class="search-body hdn" style="padding:0px 10px;">
			</div>
			<div class="chat-footer">
				<input id="search-contact" type="text" style="border:0px;margin:10px;width:90%;" placeholder="Search friends, interests, events ...">
			</div>
			<div id="broken-connect-msg" class="broken-connect<?php echo (isset($_SESSION['id']))?' hdn':'' ?>"><img src="<?php echo IMGDIR ?>exclamation.png" style="margin:2px 4px 6px 0px;opacity:0.8;float:left"  height="14" width="14">It seems the connection has lost.<span class="plain-lk pointer refresh" style="margin-left:2px;color:gray"> Refresh</span></div>
		</div>
	</div>
</div>

