<div id="chat-box" class="i-c" style="position:absolute;left:-340px;width:330px;height:400px;bottom:0px;background:#fff;overflow:hidden;border-radius:6px 6px 0px 0px; box-shadow:-2px 1px 24px #717070; ">
	<div id="chat-box-header" class="chat-header" style="padding:0px 10px;height:11%;z-index:1">
		<div class="vertical-center" style="pading-top:2px;" >
			<div class="inline-blk" style="color:#fff;"><?php echo htmlentities($fullname); ?></div>
			<div class="inline-blk pointer toggle-option" style="margin:2px 0px 0px 4px;position:relative;">
				<img src="<?php echo IMGDIR; ?>mu_icon.png" height="18" width="30">
				<div class="in_con_opt_w popover" style="top:26px; left: -90px; width:200px;font-size:13px;font-weight:normal;z-index:99">
					<div class="in_con_opt_w_inner" style="position:relative;width:100%;">
						<div class="arrow-up" style="position:absolute;top:-13px;left:91px;border-bottom:10px solid #FFFFFF"></div>
						<div class="in_con_w_opt_it remove-chatting-list">Remove from chatting list</div>
					</div>
				</div>
				
			</div>
			<div id="close-chat-box" class="inline-blk right-bar pointer"><img src="<?php echo IMGDIR; ?>white_cross_icon.png" height="12" width="12"></div>
		</div>
	</div>
	<div id="chat-box-body" class="child-scrollable">
		<?php  echo $conversations; ?>
	</div>
	<div id="chat-box-footer" style="background:#fff;height:24%;width:100%;text-align:center;border-top:1px solid #EAEAEA">
		<div class="vertical-center" ><textarea class="fcy-txt msg" style="font-size:14px;width:90%;" data-key="<?php echo $conversation_with_key ?>" ></textarea></div>
	</div>
</div>