<div id="chat-outer-wrapper" class="strech" >
	<div id="chat-side-content" style="position:relative;height:100%;width:100%;">
		<div id="chat-bar" style="height:100%;position:relative;">
			<div class="chat-header">
				<span class="title vertical-center">Messages<span>
				<span id="chat-search" class="vertical-center" title="Search Contact">
				<img src="<?php echo IMGDIR ?>search_icon.png" height="15px" width="15px">
				</span>
			</div>
			<div class="chat-body child-scrollable" style="padding:0px 10px;position:relative;overflow:scoll;height:90%;">
				<?php if($contact_block !== false): ?>
					<?php echo $contact_block; ?>
				<?php else: ?>
					<div style="margin-top:10px;font-size:13px;">
						<div style="font-size:14px;">No contact available.</div>
<!-- 
						<a href="<?php echo SEARCH_PEOPLE_PATH.$school_name ?>" class="plain-lk" style="color:rgb(180, 40, 40)">Search friends with similar interests in campus</a>
 -->
					</div>
				<?php endif; ?>
				<div id="broken-connect-overlay" class="broken-connect<?php echo (isset($_SESSION['id']))?' hdn':'' ?>">
				</div>	
			</div>
			<div class="search-body hdn" style="padding:0px 10px;">
			</div>
			<div class="chat-footer">
				<input id="search-contact" type="text" style="border:0px;margin:10px;width:90%;" placeholder="Search friends, interests, and groups...">
			</div>
			<div id="broken-connect-msg" class="broken-connect<?php echo (isset($_SESSION['id']))?' hdn':'' ?>"><img src="<?php echo IMGDIR ?>exclamation.png" style="margin:2px 4px 6px 0px;opacity:0.8;float:left"  height="14" width="14">It seems the connection has lost.<span class="plain-lk pointer refresh" style="margin-left:2px;color:gray"> Refresh</span></div>
		</div>
	</div>
</div>

