<div id="chat-outer-wrapper" class="strech" >
	<div id="chat-side-content" style="position:relative;height:100%;width:100%;">
		<div id="chat-bar">
			<div class="chat-header">
				<span class="title vertical-center">Messages<span>
				<span id="chat-search" class="vertical-center" title="Search Contact">
				<img src="<?php echo IMGDIR ?>search_icon.png" height="15px" width="15px">
				</span>
			</div>
			<div class="chat-body" style="padding:0px 10px;">
				<?php echo $contact_block; ?>
			</div>
		</div>
	</div>
</div>

