<div class="comment cmt" data-key="<?php echo $hash; ?>">
	<a href="<?php echo $user_page_redirect ?>"><img src="<?php  echo $post_owner_pic ?>" class="comment-from-picture"></a>
	<div class="inner">
		<div class="inner-container">
			<div class="visible-post-scope">
				<div class="visible-content limit-height">
				<a class="profile-name plain-lk normal-font"  href="<?php echo $user_page_redirect ?>"><?php echo htmlentities($fullname); ?>:</a>
				<span><?php echo htmlentities($text) ?></span>
				</div>
			</div>
			<div style="position:relative;top:2px;left:-2px">
				<span class="react"><?php echo $post_time ?></span>
				<?php if($user_id != $_SESSION['id']): ?>
					<span class="reply-comment react pointer">Reply</span>
				<?php endif; ?>
				<img src="<?php echo IMGDIR ?>thumb_icon.png" class="thumb" title="like" height="16" width="16"> <span></span>
				<?php if($user_id == $_SESSION['id'] || $post_owner_id == $_SESSION['id']): ?>
					<img src="<?php echo IMGDIR ?>trashcan_icon.png" class="react pointer trash-comment trashcan hdn"  height="16" width="16" title="delete this comment">
				<?php  endif; ?>
			</div>
		</div>
		<?php if($user_id != $_SESSION['id']): ?>
			<textarea class="fcy-txt comment-reply hdn" style="margin-top:12px;" data-key="<?php echo $hash; ?>" placeholder="Reply to <?php echo $fullname ?>..."></textarea>
		<?php endif; ?>
		<div class="reply-block">
			<?php echo $reply_block; ?>
		</div>
	</div>
</div>

