<div class="individual-contact contact pointer" style="padding:12px 0px 0px 0px;" data-key="<?php echo $user_iden; ?>">
	<div class="master left-bar" style="margin-right:8px;position:relative">
		<img style="border-radius:50%;" src="<?php echo $profile_pic ?>" height="36" width="36">
		<span class="n_r_s<?php echo ($new_message_num > 0)?'':' hdn' ?>" style="top:0px;left:26px;" ><?php echo $new_message_num; ?></span>
	</div>
	<div class="detail">
		<div class="vertical-center">
			<div style="width:100%;">
				<div class="txt_ofl inline-blk" style="max-width:60%;"><?php echo htmlentities($fullname); ?></div>
				<span class="time right-bar default-message" style="font-size:12px;">
					<?php if($hasMessage): ?>
						<?php echo $time ?>
					<?php endif; ?>
				</span>
			</div>
			<div class="default-message text txt_ofl">
				<?php if($hasMessage): ?>
					<?php echo htmlentities($text); ?>
				<?php endif; ?>
			</div>
		</div>
	</div>
</div>