<div id="passed-evt" class="inline-blk" style="width:82%">
	<div class="interest-content-right inline-blk" style="width: 48%;margin-left:6px;">
		<?php echo $left_content; ?>
	</div>

	<div class="interest-content-right inline-blk" style="width: 48%;margin-left:8px;">
		<?php echo $right_content; ?>
	</div>
</div>
<div id="upcom-evt" class="inline-blk hdn" style="width:82%"></div>

<div  class="inline-blk" style="width:14%;">
	<div id="show-passed-evt" class="interest-sider-navi pointer act-evt-navi" style="margin-bottom:10px;"><span class="plain-lk">Passed</span></div>
  	<div id="show-upcom-evt" class="interest-sider-navi pointer" style="margin-bottom:10px;"><span class="plain-lk">Upcomings<?php echo ($upcoming_event_num > 0)?"($upcoming_event_num)":'' ?></span></div>

</div>




