<div class="inline-blk" style="width:90%">
	<?php if($passed_event_num > 0): ?>
		<div class="interest-content-right inline-blk" style="width: 48%;margin-left:6px;">
			<?php echo $left_content; ?>
		</div>

		<div class="interest-content-right inline-blk" style="width: 48%;margin-left:8px;">
			<?php echo $right_content; ?>
		</div>
	<?php else: ?>
		<div style="background:#fff; padding:20px;">
		<?php 
			if($user_id != $_SESSION['id']){ 
				echo $firstname." has no event available";
			}else{
				echo 'You have no event available<span class="plain-lk pointer suggest-message"> Search events match your interests</span>';
			}
		?>
		</div>
	<?php endif; ?>
	
</div>



