<div class="interest-content-right inline-blk" style="width: 42%;margin-left:10px;">
<div class="post-wrapper post" style="padding:0px;margin-bottom:20px;" data-key="82bfef72d9986dfc9324d33b">
	<div>
						<img style="max-width:100%;1px 1px 3px #777777" src="http://localhost:8888/lsere_old_version/user_data/in_post_img_thumbnail/kesongxie/c8zUPFiDxhQGCew/IMG_4033.JPG">
						</div>


<div class="content">
		<div class="post-text" style="padding:0px 14px;">
			<div class="visible-post-scope">
				<div style="text-align:center;font-weight:bold;margin:10px 0px;color:rgb(114, 113, 113);font-size:20px;">Night in Madison Square Gardens</div>
				<div class="visible-content limit-height">
					<span>I went to the madison square garden #BNPParibas last night and watch the match by Roger and Drimitrov, which is entertaining and exciting.</span>
				</div>

			</div>
		</div>
		<div style="margin:10px 12px;">

		</div>
		
		<div class="moment-date" style="text-align:center;padding:10px 0px">
			March 10</div>
		

		
		<div style="padding:0px 14px 14px 14px;">
			<div class="inline-blk" style="vertical-align:bottom"><img class="post-operation-icon pointer toggle-comment" src="http://localhost:8888/lsere/media/ci.png" title="Comment" height="16" width="16"><div class="inline-blk cmt-num" style="margin:-3px 8px 0px 0px">7</div></div>
			<div class="inline-blk" style="vertical-align:bottom"><img class="post-operation-icon pointer" src="http://localhost:8888/lsere/media/favor_icon.png" title="Pin" height="18" width="18"><div class="inline-blk" style="margin-top:-1px;"></div></div>
			<div class="inline-blk pointer" style="float:right;vertical-align:bottom"><img class="e_w_b_1_c_1_a" src="http://localhost:8888/lsere/media/location_icon.png" height="17" width="17" title="Event Location">
		<div class="inline-blk" style="margin-top:-1px;"></div></div>

		</div>
		<div class="comment-block hdn" style="padding:0px 14px 14px 14px;">
			<textarea class="fcy-txt comment-txt" placeholder="Write down your thoughts..." data-key="82bfef72d9986dfc9324d33b"></textarea>
			<div class="comment-container" style="margin-top:20px;">
				
			</div>
		</div>
		
		
	</div>
	
	
	<div class="in_con_opt_w popover" style="top:34px;right:12px;">
					<div class="in_con_w_opt_it remove_activity">Remove This Moment</div>
					</div>
</div>

		<div class="post-wrapper post" style="padding:0px;" data-key="82bfef72d9986dfc9324d33b">
	<div >
						<img style="max-width:100%;1px 1px 3px #777777" src="http://localhost:8888/lsere_old_version/user_data/in_post_img_thumbnail/kesongxie/XmSRA5VeL1THF2J/IMG_3566.JPG">

								</div>
		


<div class="content">
		<div class="post-text" style="padding:0px 14px;">
			<div class="visible-post-scope">
				<div style="text-align:center;font-weight:bold;margin:10px 0px;color:rgb(114, 113, 113);font-size:20px;">US Open Champion Match</div>
				<div class="visible-content limit-height">
					<span>I spent a night in the beautiful Huston River park tennis court. I have been always enjoyed playing tennis here. Nice sunset.</span>
				</div>

			</div>
		</div>
		<div style="margin:10px 12px;">
	<!-- 
	<div style="padding:6px 0px;">
		<img class="e_w_b_1_c_1_a" src="http://localhost:8888/lsere/media/location_icon.png" height="17" width="17" title="Event Location">
		
 <div class="inline-blk">USTA Billie Jean King National Tennis Center</div>
		</div>
	
 -->	<!-- 
<div style="padding:6px 0px;">
		<img  src="http://localhost:8888/lsere/media/date_icon.png" height="15" width="15" title="Event Location">
		

		<div class="inline-blk">Saturday, 11:00 AM</div>
		</div>
		
 -->
		</div>
		
		<div class="moment-date" style="text-align:center;padding:10px 0px">
			Jun 26 </div>
		

		
		<div style="padding:0px 14px 14px 14px;">
			<div class="inline-blk" style="vertical-align:bottom"><img class="post-operation-icon pointer toggle-comment" src="http://localhost:8888/lsere/media/ci.png" title="Comment" height="16" width="16"><div class="inline-blk cmt-num" style="margin:-3px 8px 0px 0px">7</div></div>
			<div class="inline-blk" style="vertical-align:bottom"><img class="post-operation-icon pointer" src="http://localhost:8888/lsere/media/favor_icon.png" title="Pin" height="18" width="18"><div class="inline-blk" style="margin-top:-1px;"></div></div>
			<div class="inline-blk pointer" style="float:right;vertical-align:bottom"><img class="e_w_b_1_c_1_a" src="http://localhost:8888/lsere/media/location_icon.png" height="17" width="17" title="Event Location">
		<div class="inline-blk" style="margin-top:-1px;"></div></div>

		</div>
		<div class="comment-block hdn" style="padding:0px 14px 14px 14px;">
			<textarea class="fcy-txt comment-txt" placeholder="Write down your thoughts..." data-key="82bfef72d9986dfc9324d33b"></textarea>
			<div class="comment-container" style="margin-top:20px;">
				
			</div>
		</div>
		
		
	</div>
	
	
	<div class="in_con_opt_w popover" style="top:34px;right:12px;">
					<div class="in_con_w_opt_it remove_activity">Remove This Moment</div>
					</div>
</div>
			</div>



<div class="interest-content-right inline-blk" style="width: 42%;margin-left:10px;">
		<div class="post-wrapper post" style="padding:0px;" data-key="82bfef72d9986dfc9324d33b">
	<div>
						<img style="max-width:100%;1px 1px 3px #777777" src="http://localhost:8888/lsere_old_version/user_data/in_post_img_thumbnail/kesongxie/firVKn6HGsphXja/IMG_3172.jpg">
						</div>


<div class="content">
		<div class="post-text" style="padding:0px 14px;">
			<div class="visible-post-scope">
				<div style="text-align:center;font-weight:bold;margin:10px 0px;color:rgb(114, 113, 113);font-size:20px;">Trace Bundy Guitar Concert</div>
				<div class="visible-content limit-height">
					<span>My first acoustic guitar concert in the United States is of Trace Bundy's in the amazing venue. He played my beloved Canon in D and show off his guitar skill on a I phone app with a song by metablica</span>
				</div>

			</div>
		</div>
		<div style="margin:10px 12px;">

		</div>
		
		<div class="moment-date" style="text-align:center;padding:10px 0px">
			May 10 - 2014 </div>
		

		
		<div style="padding:0px 14px 14px 14px;">
			<div class="inline-blk" style="vertical-align:bottom"><img class="post-operation-icon pointer toggle-comment" src="http://localhost:8888/lsere/media/ci.png" title="Comment" height="16" width="16"><div class="inline-blk cmt-num" style="margin:-3px 8px 0px 0px">7</div></div>
			<div class="inline-blk" style="vertical-align:bottom"><img class="post-operation-icon pointer" src="http://localhost:8888/lsere/media/favor_icon.png" title="Pin" height="18" width="18"><div class="inline-blk" style="margin-top:-1px;"></div></div>
			<div class="inline-blk pointer" style="float:right;vertical-align:bottom"><img class="e_w_b_1_c_1_a" src="http://localhost:8888/lsere/media/location_icon.png" height="17" width="17" title="Event Location">
		<div class="inline-blk" style="margin-top:-1px;"></div></div>

		</div>
		<div class="comment-block hdn" style="padding:0px 14px 14px 14px;">
			<textarea class="fcy-txt comment-txt" placeholder="Write down your thoughts..." data-key="82bfef72d9986dfc9324d33b"></textarea>
			<div class="comment-container" style="margin-top:20px;">
				
			</div>
		</div>
		
		
	</div>
	
	
	<div class="in_con_opt_w popover" style="top:34px;right:12px;">
					<div class="in_con_w_opt_it remove_activity">Remove This Moment</div>
					</div>
</div>
			</div>
