<div class="in_con_w_opt_it invited-list popover-list" style="padding: 10px 10px;cursor:default;" data-key="<?php echo $hash; ?>">
	<img class="label-image" src="<?php echo $profile_pic; ?>">
	<div class="inline-blk txt_ofl name" data-key="<?php echo $key ?>" style="width: 104px;margin-top:3px;font-size:13px;"><?php echo $fullname ?></div>
	<img class="remove-from-invitation pointer animate-opacity remove-from hdn" src="<?php echo IMGDIR ?>minus_icon.png" title="Undo invitation" height="16" wdith="16" style="float:right;margin-top:4px;">
</div>