<div class="inner inline-blk">
	<div  class="header">
		<div class="title vertical-center inline-blk">Invite People</div>
		
		<div class="vertical-center" style="float: right;position:relative">
			<div id="selected-bar">
				<div id="bar-icon-wrapper" class="inline-blk">
				<span id="invitation-invited-bar-wrapper" class="pointer" ><span id="invitation-invited-num" data-num = "<?php echo $invitation_num ?>"><?php echo $invitation_num ?></span> Invited</span>
				<span> - </span>
				<div id="toggle-selected-detail" class="inline-blk pointer" >
					<span id="invitation-selected-bar-wrapper" class="red-act"><span id="invitation-selected-num" class="red-act">0</span> Selected</span>
					<div id="selected-preview-wrapper" class="inline-blk"></div>
				</div>
				</div>
			</div>
		
		<div id="invited-detail" class="in_con_opt_w popover hdn" style="top: 37px; left: -72px; display: block;width:200px;box-shadow:-1px -1px 17px #D4D4D4;border-radius:6px;"> 
			<div class="in_con_opt_w_inner" style="position:relative;width:100%;">
				<div class="arrow-up" style="position:absolute;top:-15px;left:88px;border-bottom:10px solid #FFFFFF"></div>
				<div class="inner-w" style="position: relative; overflow: hidden; width: 100%;">
					<!--starts int-group-->
					<div class="sub" style="margin-top: 6px;">
						<div class="sub-inner" style="max-height:338px; overflow:scroll;font-size:14px;">
							
						</div> <!--ends max-height -->
					</div> 
				</div>
			</div><!--ends inner-w-->
		</div>	
			
			
		
		<div id="selected-detail" class="in_con_opt_w popover hdn" style="top: 37px; right: 16px; display: block;width:200px;box-shadow:-1px -1px 17px #D4D4D4;border-radius:6px;"> 
			<div class="in_con_opt_w_inner" style="position:relative;width:100%;">
				<div class="arrow-up" style="position:absolute;top:-15px;right:31px;border-bottom:10px solid #FFFFFF"></div>
				<div class="inner-w" style="position: relative; overflow: hidden; width: 100%;">
					<!--starts int-group-->
					<div class="sub" style="margin-top: 6px;">
						<div class="sub-inner" style="max-height:338px; overflow:scroll;font-size:14px;">
							
						</div> <!--ends max-height -->
					</div> 
				</div>
			</div><!--ends inner-w-->
		</div>
			
		</div>
 
 

		
	</div>
	<div class="body" style="font-size:0px;clear:both">
		<div class="left-content inline-blk">
			<div style="margin-left:6px;">
			<div class="all-friend pointer group-label active" data-key="-1"><span class="plain-lk">All Friends</span></div>
			<div class="inner-w" style="position: relative; width: 100%;">
				<!--starts int-group-->
				<div class="sub" style="margin-top: 6px;">
					<?php if($labels !== false && sizeof($labels) > 0): ?>
						<?php foreach($labels as $label): ?>
							<div class="interest-side-label in_con_w_opt_it pointer group-label" style="padding:8px 10px;" data-key="<?php echo $label['id'] ?>" title="<?php echo htmlentities($label['name']) ?>">
								<img class="label-image" src="<?php echo $label['picture_url'] ?>">
								<div class="inline-blk txt_ofl" style="width:95px;margin-top:4px;font-size:13px;"><?php echo htmlentities($label['name']) ?></div>
							</div>
						<?php endforeach; ?>
					<?php endif; ?>
				</div> 
			</div>
		</div>
	
		<div id="invitation-search-wrapepr">
				<div class="vertical-center inline-blk" style="margin-left:12px;">
				<img src="<?php echo IMGDIR; ?>search_icon.png" title="search" style="z-index:1;height:14px; width:14px;cursor:pointer">
			</div>
			<div class="vertical-center inline-blk" style="margin:1px 0px 0px 6px;">
				<input type="text" style="border:0px;width: 121%;" placeholder="Search friends or email">
			</div>
		</div>
	
		</div>
		<div class="right-content inline-blk">
			<div class="contact">
				<div class="contact-inner content-inner" style="margin:14px;">
					<?php echo $all_friend_block; ?>
				</div>
				<div class="suggest-contact-inner hdn content-inner" style="margin:14px;"></div>				
			</div>
			
			<div class="option-wrapper">

				<div class="vertical-center inner-option-wrapper" style="text-align:right;">
 					<div class="after-action hdn">
						<div class="inline-blk silver-button cancel-button popup-button dismiss" style="margin-right:6px"><img src="<?php echo IMGDIR ?>plane_sent_icon.png" class="request-sent" style="margin-right:4px;" >Invitation Sent, Okay</div>
					</div>
					<div class="before-action">
						<div class="inline-blk silver-button cancel-button popup-button dismiss" style="margin-right:6px">Cancel</div>
						<div class="inline-blk action-button popup-button un-requestable invite-button" style="margin:0px 10px 0px 0px;">Invite</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
