<div class="media-asset">
	<div class="navigate" style="position:absolute;top:0px;height:100%;left:-60px;">
	<img src="<?php echo IMGDIR ?>prev.png"  class="gallery-navi left vertical-center"  height="20" width="20">
	</div>
	<div class="navigate" style="position:absolute;top:0px;height:100%;right:-60px;"><img src="<?php echo IMGDIR ?>nxt.png"  class="gallery-navi right vertical-center"  height="20" width="20"></div>
	<div class="preview-image-wrapper" ><img  src="" class="preview-image hdn" data-prev = "<?php echo $previous_photo_hash ?>" data-nxt="<?php echo $next_photo_hash ?>" /></div>
	
	<div class="caption" style="position:absolute;bottom:-24px;right:10px;opacity:0.6;font-size:13px;"><?php echo htmlentities($caption) ?></div>
</div>
<div class="media-detail" style="text-align:left;background:#fff;min-height:100px;border-radius:0px 0px 6px 6px;">
	<div class="media-detial-container" style="padding:20px;margin-left:60px;">
		<a class="dummy-lk" href="<?php echo $user_page_redirect ?>"><img  style="height: 44px; width: 44px;float:left;margin:0px 14px 14px 0px; border-radius: 6px;margin-left:-60px;" src="<?php echo $profile_pic ?>">
		<div class="profile-name pointer post-user-name inline-blk"><?php echo htmlentities($fullname) ?></div></a>
		<div class="inline-blk" style="  margin-left: 10px;  color: #969696;"><?php echo $post_time ?></div>
		<div class="visible-post-scope">
			<div class="visible-content limit-height">
				<div><?php echo htmlentities($row['description']); ?></div>
				<div style="padding:18px 0px">
					<div><?php echo htmlentities($row['location']); ?></div>
					<div><?php echo htmlentities($time); ?></div>
				</div>
			</div>
		</div>
	</div>
</div>