<div class="inline-blk pht">
	<!--first image-->
	<?php $displayable = isMediaDisplayable($regular_event_photo); ?>

	<?php if($displayable): ?>
		<img class="vertical-center display-img" style="max-width:90%;max-height:90%;" src="<?php echo U_IMGDIR.$regular_event_photo ?>">
	<?php endif;?>
</div>
<div class="inline-blk ct">
	<div class="pointer cross" style="position:absolute;right:4px;top:4px;"><img src="<?php echo IMGDIR ?>cross_icon.png" style="height:20px;width:20px;" title="Close" /></div>
	<div class="title" style="margin:20px 26px 0px 26px;font-size:20px;"><?php echo $title; ?></div>
	<div class="desc"  style="margin:20px 26px 0px 26px;font-size:16px;"><?php echo $description; ?></div>
	<div class="date" style="text-align:right;margin:20px 30px 0px 30px;font-weight:600;font-size:16px;">
		
		<?php if($isEventEditableForCurrentUser && $isEventPassed): ?>
			<label class="upload-evt-pic-label">
				<img class="upload-evt-pic-camera" src="<?php echo IMGDIR ?>camera_icon.png" title="Add photo to this event collection">
				<form method="POST" class="hdn-form" enctype="multipart/form-data">
					<input class="upload-evt-pic hdn-input"  type="file" name="picture-label" title="Add photo to this event collection">
				</form>
			</label>
		<?php endif; ?>
		
		<span><?php echo $date ?><span>
	</div>
	<div class="ct-pht-all">
		<!--all images-->
		<div class="inline-blk thumb-evt-pht evt-pht-new-frame hdn" >
			<div class="target-container hdn" style="height:100%;width:100%;background:#fff;"><img src="" class="target-image" style="height:100%;"></div>
			<div class="preview-loading-wrapper" style="position:absolute;top:0px;left:0px;width:100%;height:100%;background:#fff;opacity:0.6;">
				<div class="center-align vertical-center"><img src="<?php echo IMGDIR ?>animated-loading-bar.gif" width="22" height="22"></div>
			</div>
		</div>
		
		<?php foreach($photos as $photo):  ?>
		<div class="inline-blk thumb-evt-pht thumb" data-key="<?php echo $photo['hash'] ?>">
			<img class="vertical-center" style="height:100%" src="<?php echo U_IMGDIR.$photo['url']; ?>">
			<?php if($isEventEditableForCurrentUser): ?>
			<img src="<?php echo IMGDIR ?>c_icon.png" class="remove-evt-pht pointer animate-opacity hdn">
			<?php endif; ?>
		</div>
		<?php endforeach; ?>
	</div>
</div>