<div id="favor-evt-block" style="padding:10px 10px 12px 10px;margin-top:20px;" >
	<div>
		<span style="color:#1E1E1E;font-weight:bold;font-size:16px;" title="Recent favorite hangout event" >Favorite Events</span>
		<img id="show-favor-evt-edit" class="favor-evt-ic pointer" src="<?php echo IMGDIR ?>add_icon.png" height="14" width="14" title="Add favorite event" style="float:right;margin-top:2px;">
		<img id="hide-favor-evt-edit" class="favor-evt-ic pointer hdn" src="<?php echo IMGDIR ?>minus_icon.png" height="18" width="18" title="Cancel editting favorite event" style="float:right;margin-top:2px;">
	</div>
	<div id="add-favor-evt" class="hdn" style="width:100%;background:#fff;margin-top:10px">
		<div class="popover-throwable" style="position:relative;margin-bottom:10px;">
			<div style="width:100%;"><input type="text" class="fcy-txt" placeholder="Add a short title..." maxlength="32"></div>
		</div>
		<div class="popover-throwable" style="position:relative;">
			<div style="width:100%;"><textarea class="fcy-txt" style="height:60px;display:block;" placeholder="Add some description..."></textarea></div>
		</div>
	</div>
	
	<?php if($evts !== false && sizeof($evts) > 0): ?>
	<div id="favor-evt-label-wrapper">
		<?php foreach($evts as $evt): ?>
		<div class="favor-evt-wrapper" style="position:relative;margin-right:10px;" data-key="<?php echo $evt['hash'] ?>">
			<span class="favor-evt-label plain-lk ">#<?php echo htmlentities($evt['title']) ?></span>
		</div>
		<?php endforeach; ?>
	</div>	
	<?php else: ?>
	
		<?php if($user_id == $_SESSION['id']): ?>
		<div style="background:#fff;position:relative" >
<!-- 
			You haven't added your favorite events yet, <span href="" class="plain-lk pointer" style="color:#062AA3">Let your friend know</span>
 -->
		</div>
		<?php endif; ?>
	<?php endif; ?>
</div>