<div class="time_picker_outer_wrapper popover hdn">
		<div class="time_picker_inner_header">
			Select Time
		</div>
		<div class="time_picker_inner_body">
			<div class="time_picker_inner_wrapper">
				<div class="time_picker_time_part">
				<div class="time_picker_item">00:30</div><div class="time_picker_item asct">01:00</div><div class="time_picker_item">01:30</div><div class="time_picker_item">02:00</div><div class="time_picker_item">02:30</div><div class="time_picker_item">03:00</div><div class="time_picker_item">03:30</div><div class="time_picker_item">04:00</div><div class="time_picker_item">04:30</div><div class="time_picker_item">05:00</div><div class="time_picker_item">05:30</div><div class="time_picker_item">06:00</div><div class="time_picker_item">06:30</div><div class="time_picker_item">07:00</div><div class="time_picker_item">07:30</div><div class="time_picker_item">08:00</div><div class="time_picker_item">08:30</div><div class="time_picker_item">09:00</div><div class="time_picker_item">09:30</div><div class="time_picker_item">10:00</div><div class="time_picker_item">10:30</div><div class="time_picker_item">11:00</div><div class="time_picker_item">11:30</div><div class="time_picker_item">12:00</div></div>
				
				<div class="time_picker_ampm_part">
					<div class="ampm_part_item asct">AM</div>
					<div class="ampm_part_item">PM</div>
				</div>
			</div>
		</div>
	</div>
<div id="preview-popup-overlay" class="overlay ol hdn" style="opacity:1; background-color:rgba(0,0,0,.82);position:fixed !important"></div>	
<div id="evt-preview" class="preview-dialog dl vertical-center evt-block hdn"></div>

<div id="photo-preview" class="preview-dialog dl hdn">
	<div class="content-wrapper vertical-center" style="margin:0px auto;width:50vw;min-width:600px;">
	</div>
</div>




<div id="dialog-popup-overlay" class="overlay ol hdn"></div>	
<div id="popup-dialog-wrapper" class="vertical-center dl hdn"style="position:fixed;width:100%;margin-top:-40px;z-index:10001;text-align:center;"></div>

<div class="hover-avator-wrapper hdn" style="z-index:9999;position:absolute">
</div>