<div class="overlay hdn" style="background:#000;z-index:99;opacity:0.4;"></div>
<div id="edit-dialog-wrapper" class="vertical-center hdn">
	<div id="edit-dialog-wrapper-inner" class="inline-blk">
	<div id="edit-profile-dialog-wrapper" class="segue-wrapper inline-blk">
		<div class="segue-main segue">
			<div class="dialog-title">
				<div class="dialog-title-text">Edit Profile</div>
			</div>
			<div style="width:100%;overflow:hidden">
				<img style="width:100%;margin-top:-70%;display: block;" src="http://localhost:8888/media/dummy/1.jpeg">
			</div>
		
			<div style="margin:-60px 0px 10px 20px;text-align:left">
				<div class="inline-blk" style="border:6px solid #fff;border-radius:3px;">
					<img  src="<?php echo DUMMY_MEDIA ?>avator.jpg" style="height:80px;width:80px;">
				</div>
				<div style="font-weight: 600;font-size: 18px; color: #223D50; margin-left: 3px;">Jamie Liang</div>
			</div>
			<div style="border-top:1px solid #eaeaea;padding:10px 24px;">
				<div>
					<div id="edit-short-bio" class="two-rows-box content-editable entry-focus" contenteditable="true" style="text-align:left;min-height:48px;" data-end = "true" placeholder="Short bio" ></div>
				</div>
			</div>
		
			<div id="add-scene-bar" class="option-bar">
				<div style="position:relative;cursor:default;">
					<input style="width:100%;border:0px;position:relative;left:0px;background:inherit" readonly placeholder="Travel, Beauty, Supreme"/>
					<span style="position:absolute;right:0px;top:0px;color: #B0B0B0;">Edit<img src="<?php echo IMGDIR; ?>right_nxt.png" height="16" width="16" style="position:relative;top:2px;margin-left:2px;" /></span>
				</div>
			</div>
			<div style="border-top:1px solid #eaeaea;padding:10px 24px;text-align:right">
				<div>
					<button id="cancel-e-p-button" class="animated-button gray-action-button" style="padding:0px 20px;margin-right:6px;">CANCEL</button>

					<button id="save-e-p-button" class="animated-button blue-action-button" style="padding:0px 34px;">SAVE</button>
				</div>
			</div>
		</div>
		<div id="add-scene-segue" class="segue-detail segue" style="position:absolute;right:-100%;top:0px;width:100%;" >
			<div class="dialog-title"  >
				<div class="segue-to-main segue-to-main-action"><img src="<?php echo IMGDIR; ?>left_nxt.png" height="16" width="16" style="position: relative;top: 2px;margin-right:3px;"/>Cancel</div>
				<div class="dialog-title-text">Add Scene Labels</div>
			</div>
			<div class="dialog-body" style="height:300px;">
					<div style="border-bottom:1px solid #eaeaea;padding:10px 24px;">
						<div>
							<input style="width:100%;border:0px;"  placeholder="Enter a scene lable name, such as music, travel, etc"/>
						</div>
					</div>
					<div class="bb-list">
						<div>
							<div class="label-red" style="">Travel (5 Scenes)</div>
						</div>
					</div>
					
					
					<div class="bb-list">
						<div>
							<div class="label-red" style="">Beauty (1 Scene)</div>
						</div>
					</div>
					
					<div class="bb-list">
						<div>
							<div class="label-red" style="">Supreme</div>
						</div>
					</div>
			</div>
			
			<div class="" style="border-top:1px solid #eaeaea;padding:10px 24px;text-align:right">
				<div>
					<button class="animated-button blue-action-button segue-to-main-action" style="padding:0px 30px;">DONE</button>
				</div>
			</div>
		</div>
	</div>
	
	<div id="add-scene-dialog-wrapper" class="segue-wrapper inline-blk" >
		<div class="segue-main segue act">
			<div class="dialog-title">
				<div class="dialog-title-text">Add Scene</div>
			</div>
			<div id="attach-post-photo-banner" style="width:100%;overflow:hidden;position:relative;height:128px;font-size:0px;background-color: #000;">
				<label for="attach-post-photo" id="attach-post-photo-label">
					<div class="inline-blk vertical-center"><img src="<?php echo IMGDIR; ?>camera.png" height="25" width="29"><div style="font-size:16px;font-weight:600;color:#fff">Attach <span class="expand-text">Photos</span></div></div>
					<form method="POST" style="display:none" enctype="multipart/form-data">
						<input id="attach-post-photo" class="hdn-input" type="file" name="attach-post-photo" >
					</form>
				</label>
			</div>
			
			<div style="border-top:1px solid #eaeaea;padding:10px 24px;">
				<div>
					<div  class="two-rows-box content-editable entry-focus" contenteditable="true" style="text-align:left;min-height:48px;" data-end = "true" placeholder="What's in the scene?" ></div>
				</div>
			</div>
			
		
			<div class="option-bar">
				<div style="position:relative;cursor:default;">
					<input style="width:100%;border:0px;position:relative;left:0px;background:inherit" readonly placeholder="December 23, 2015"/>
					<span style="position:absolute;right:0px;top:0px;color: #B0B0B0;">Edit<img src="<?php echo IMGDIR; ?>right_nxt.png" height="16" width="16" style="position:relative;top:2px;margin-left:2px;" /></span>
				</div>
			</div>
			
			<div id="add-scene-bar" class="option-bar">
				<div style="position:relative;cursor:default;">
					<input style="width:100%;border:0px;position:relative;left:0px;background:inherit" readonly placeholder="Location for this scene"/>
					<span style="position:absolute;right:0px;top:0px;color: #B0B0B0;">Edit<img src="<?php echo IMGDIR; ?>right_nxt.png" height="16" width="16" style="position:relative;top:2px;margin-left:2px;" /></span>
				</div>
			</div>
			
			<div style="border-top:1px solid #eaeaea;padding:10px 24px;text-align:right">
				<div>
					<button id="cancel-e-p-button" class="animated-button gray-action-button" style="padding:0px 20px;margin-right:6px;">CANCEL</button>

					<button id="save-e-p-button" class="animated-button blue-action-button" style="padding:0px 34px;">ADD</button>
				</div>
			</div>
		</div>
	
		<div id="post-photo-layout-segue" class="segue-detail segue" style="position:absolute;right:-100%;top:0px;width:100%;" >
			<div class="dialog-title"  >
				<div class="segue-to-main segue-to-main-action"><img src="<?php echo IMGDIR; ?>left_nxt.png" height="16" width="16" style="position: relative;top: 2px;margin-right:3px;"/>Done</div>
				<div class="dialog-title-text" data-default-title="Layout Photos">Layout Photos</div>
			</div>
			<div id="layout-draggable" class="dialog-body photo-layout-body" style="overflow:hidden;cursor:move;height:512px;font-size:0px;">
				
				<div class="photo-segment-container inline-blk two-column-horizon hdn" data-container-queue = "1">
					<div class="photo-segment"  data-segment-queue = "1">
						<img class="photo" src="" >
					</div>
				</div>
				
				<div class="photo-segment-container inline-blk two-column-horizon hdn" data-container-queue = "2">
					<div class="photo-segment"  data-segment-queue = "2">
						<img class="photo" src="" >
					</div>
				</div>
				
				
			</div>
			
			<div class="hdn" style="border-top:1px solid #eaeaea;padding:10px 24px;text-align:right;">
				<div>
					<button class="animated-button blue-action-button segue-to-main-action" style="padding:0px 30px;">DONE</button>
				</div>

			</div>
		</div>

	
	
	
	
	</div>
	</div>
</div>