<div id="friend-content-wrapper" class="inline-blk" style="width:<?php echo ($user_has_friend)?'80%':'100%';?>">
		<?php echo $content; ?>
</div>

<?php if($user_has_friend): ?>
<div id="friend-interest-navi" class="interest-navi inline-blk" style="text-align:left;width:18%;">
		<div id="all-friend-label" class="interest-sider-navi pointer<?php echo ($active_interest_id == -1)?' active':'' ?>"  data-labelfor="-1" data-href="<?php echo $user_profile_url.'/friends'; ?>" style="color: #797979; font-weight: bold;"><span class="plain-lk">All Friends</span></div>
	<?php if($user_interests !== false): ?>
	<?php foreach($user_interests as $user_interest): ?>
		<div class="interest-side-label interest-sider-navi pointer<?php echo ($active_interest_id == $user_interest['id'])?' active':'' ?>" data-labelfor="<?php echo $user_interest['id'];?>" data-href="<?php echo $user_interest['data_href']; ?>"  title="<?php echo htmlentities($user_interest['name']);?>"><div class="vertical-center"><img src="<?php echo $user_interest['picture_url']; ?>"><div class="inline-blk txt_ofl<?php echo ($active_interest_id == $user_interest['id'])?' red-act':''; ?>" style="width:95px;margin-top:3px;font-size:13px;"><?php echo htmlentities($user_interest['name']);?></div></div></div>
 	<?php  endforeach;  //end display side ?>
	<?php endif ?>
</div>

<?php endif; ?>
