<div class="friend-content-inner-wrapper blk" data-key="<?php echo $interest_id; ?>">
	<?php if($content !== false):?>
		<?php echo $content; ?>
	<?php else: ?>
		<div style="background:#fff; padding:20px;">
			There is no friends in this interest group
			<?php if($user_id == $_SESSION['id']): ?>
			 <a href="<?php echo SEARCH_PEOPLE_PATH.htmlentities($interest_name) ?>" class="plain-lk pointer" style="color:#062AA3">Find friends who interested in <?php echo htmlentities($interest_name) ?>?<a>
			<?php endif; ?>
		</div>
	<?php endif; ?>
	<div class="feed-loading-wrapper hdn" style="text-align:center;margin-top:20px;"><img src="<?php echo SPINNER_ICON ?>" height="72" width="96"></div>

</div>