<div class="friend-content-inner-wrapper blk" data-key="-1">
	<?php if($content !== false):?>
		<?php echo $content; ?>
	<?php else: ?>
		<div style="background:#fff; padding:20px;">
			No friends have been added yet.
			<?php if($user_id == $_SESSION['id']): ?>
			 <a href="<?php echo SEARCH_SIMILAR_PEOPLE_PATH; ?>" class="plain-lk pointer" style="color:#062AA3">Find friends that match your interests<a>
			<?php endif; ?>
		</div>
	<?php endif; ?>
	<div class="feed-loading-wrapper hdn" style="text-align:center;margin-top:20px;"><img src="<?php echo SPINNER_ICON ?>" height="72" width="96"></div>

</div>