<div class="chat-header" style="padding:0px 10px;height:11%;z-index:1;text-align:center">
	<div class="vertical-center" style="padding-top:2px;font-size:14px;" >
		<div class="inline-blk txt_ofl back-to-main" style="color:#fff;max-width:74%;float:left;cursor:default;"><img src="<?php echo IMGDIR ?>left_nxt.png" style="margin-top:4px;margin-right: 2px;opacity: 0.6;" height="12" width="12"><span style=" margin-right: 38px;">Chat</span></div>
		<div class="inline-blk" style="color:#fff;margin-left:-48px;">Joined Members</div>
		<div class="inline-blk pointer toggle-option" style="margin:2px 0px 0px 4px;position:relative;float:right">
			<img src="<?php echo IMGDIR; ?>mu_icon.png" height="18" width="30">
			<div class="in_con_opt_w popover">
				<div class="in_con_opt_w_inner" style="position:relative;width:100%;">
					<div class="arrow-up"></div>
					<div class="in_con_w_opt_it event-info">Event Details</div>
					<div class="in_con_w_opt_it joined-member">Joined Members</div>
					<div class="in_con_w_opt_it remove-chatting-list">Remove from chatting list</div>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="chat-member" style="height:89%">
	<div style="padding:14px;overflow:scroll"><?php echo $chat_members; ?></div>
</div>



	