<div id="chat-box" class="g-c" style="position:absolute;left:-340px;width:330px;height:400px;bottom:0px;background:#fff;border-radius:6px 6px 0px 0px; box-shadow:-2px 1px 24px #717070; ">
	<div id="main-conversation" style="width:100%;height:100%">
		<div id="chat-box-header" class="chat-header" style="padding:0px 10px;height:11%;z-index:1;">
			<div class="vertical-center" style="padding-top:2px;" >
				<div class="inline-blk txt_ofl" style="color:#fff;max-width:74%;font-size:14px;" title="<?php echo htmlentities($title); ?>"><?php echo htmlentities($title); ?></div>
				<div class="inline-blk pointer toggle-option" style="margin:2px 0px 0px 4px;position:relative">
					<img src="<?php echo IMGDIR; ?>mu_icon.png" height="18" width="30">
					<div class="in_con_opt_w popover hdn" >
						<div class="in_con_opt_w_inner" style="position:relative;width:100%;">
							<div class="arrow-up" ></div>
							<div class="in_con_w_opt_it event-info">Event Details</div>
							<div class="in_con_w_opt_it joined-member">Joined Members</div>
							<div class="in_con_w_opt_it remove-chatting-list">Remove from Chatting List</div>
						</div>
					</div>
				</div>
				<div id="close-chat-box" class="inline-blk right-bar pointer"><img  src="<?php echo IMGDIR; ?>white_cross_icon.png" height="12" width="12"></div>
			</div>
		</div>
		<div id="chat-box-body" class="child-scrollable">
			<?php  echo $conversations; ?>
		</div>
		<div id="chat-box-footer" style="background:#fff;height:24%;width:100%;text-align:center;border-top:1px solid #EAEAEA">
			<div class="vertical-center" ><textarea class="fcy-txt msg" style="font-size:14px;width:90%;" data-key="<?php echo $group_key ?>" ></textarea></div>
		</div>
	</div>
	<div id="side-member" class="hdn" style="width:100%;height:100%"></div>
	<div id="side-event-info" class="hdn" style="width:100%;height:100%"></div>
</div>