<div class="group-contact contact pointer" style="padding:12px 0px 0px 0px;height:40px;" data-key="<?php echo $hash; ?>">
	<div class="master left-bar" style="margin-right:8px;position:relative">
		<div style="position:relative;top:6px;left:1px;">
		<img style="border-radius:50%;position:absolute;top:-10px;left:10px;z-index:-1" src="<?php echo $second_user_profile ?>" height="30" width="30">
		<img style="border-radius:50%;" src="<?php echo $first_user_profile ?>" height="32" width="32">
		</div>
		<span class="n_r_s<?php echo ($new_message_num > 0)?'':' hdn' ?>" style="top:0px;left:26px;" ><?php echo $new_message_num ?></span>
	</div>
	<div class="detail" style="float:right;width:78%">
		<div class="vertical-center">
			<div style="width:100%;">
				<div class="txt_ofl inline-blk" style="<?php echo ($hasMessage)?'max-width:74%':'max-width:100%';?>"><?php echo htmlentities($group_title) ?></div>
				<span class="time right-bar default-message" style="font-size:12px;">
					<?php if($hasMessage): ?>
						<?php echo $time; ?>
					<?php endif; ?>
				</span>
			</div>
			<div class="default-message text txt_ofl">
				<?php if($hasMessage): ?>
					<?php echo htmlentities($text);?>
				<?php endif; ?>
			</div>
		</div>
	</div>
</div>