<div class="contact pointer" style="padding:12px 0px 0px 0px;" data-key="<?php ?>">
	<div class="master left-bar" style="margin-right:8px;position:relative">
		<div style="position:relative;top:6px;left:-1px;">
		<img style="border-radius:50%;position:absolute;top:-10px;left:10px;z-index:-1" src="http://localhost:8888/lsere/media_u/597394f9fe626bbb1f13c37f/4358d1f8e26a23e87ad92964/thumb_6e90cee991f25c6c904eabbb.jpg" height="30" width="30">
		<img style="border-radius:50%;" src="http://localhost:8888/lsere/media_u/0b6b58a7d212e078ed4662cb/406867654e08b646857e431d/thumb_be08ebe9354ca99c168b0976.jpg" height="32" width="32">
		</div>
		<span class="n_r_s" style="top:0px;left:26px;" ><?php echo 1 ?></span>

	</div>
	<div class="detail" style="float:right;width:78%">
		<div class="vertical-center">
			<div style="width:100%;">
				<div class="txt_ofl inline-blk" style="max-width:60%;">US Open 2015 in September</div>
				<span class="time right-bar default-message" style="font-size:12px;">
					6 h
				</span>
			</div>
			<div class="default-message text txt_ofl">
				Can't wait for this exciting event
			</div>
		</div>
	</div>
</div>