<div class="group-contact contact pointer" style="padding:12px 0px 0px 0px;height:40px;position: relative;" data-key="<?php echo $hash; ?>">
	<div class="master left-bar inline-blk" style="margin-right:8px;width:18%;">
		<img style="border-radius:50%;    margin-left: 11px; margin-bottom: -4px;" src="<?php echo $second_user_profile ?>" height="30" width="30">
		<img style="border-radius:50%;margin-top: -20px" src="<?php echo $first_user_profile ?>" height="32" width="32">
		<span class="n_r_s<?php echo ($new_message_num > 0)?'':' hdn' ?>" style="left:26px;top:18px;" ><?php echo $new_message_num ?></span>
	</div>
	<div class="detail" style="float:right;width:76%;margin-top:6px;">
		<div class="vertical-center">
			<div style="width:100%;">
				<div class="txt_ofl inline-blk" style="<?php echo ($hasMessage)?'max-width:74%':'max-width:100%';?>"><?php echo htmlentities($group_title) ?></div>
				<span class="time right-bar default-message" style="font-size:12px;">
					<?php if($hasMessage): ?>
						<?php echo $time; ?>
					<?php endif; ?>
				</span>
			</div>
			<div class="default-message text txt_ofl">
				<?php if($hasMessage): ?>
					<?php echo htmlentities($text);?>
				<?php endif; ?>
			</div>
		</div>
	</div>
</div>