<div class="chat-header" style="padding:0px 10px;height:11%;z-index:1;text-align:center">
	<div class="vertical-center" style="padding-top:2px;font-size:14px;" >
		<div class="inline-blk txt_ofl back-to-main" style="color:#fff;max-width:74%;float:left;cursor:default;"><img src="<?php echo IMGDIR ?>left_nxt.png" style="margin-top:4px;margin-right: 2px;opacity: 0.6;" height="12" width="12"><span style=" margin-right: 38px;">Chat</span></div>
		<div class="inline-blk" style="color:#fff;margin-left:-48px;">Event Details</div>
		<div class="inline-blk pointer toggle-option" style="margin:2px 0px 0px 4px;position:relative;float:right">
			<img src="<?php echo IMGDIR; ?>mu_icon.png" height="18" width="30">
			<div class="in_con_opt_w popover hdn">
				<div class="in_con_opt_w_inner" style="position:relative;width:100%;">
					<div class="arrow-up"></div>
					<div class="in_con_w_opt_it event-info">Event Details</div>
					<div class="in_con_w_opt_it joined-member">Joined Members</div>
					<div class="in_con_w_opt_it remove-chatting-list">Remove from chatting list</div>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="event-info-body evt-block child-scrollable" style="height:89%;overflow:scroll">
 	<div style="margin:14px;">
		<img src="<?php echo $resource['event_photo_url']; ?>" style="float:left;margin:0px 6px 100000px 0px" height="36" width="36">
		<div style="border-bottom:1px solid #f0f0f0;padding-bottom:10px;">
			<div>
				<div class="visible-post-scope">
					<div style="font-size:12px;font-weight:600;color:#3A3637;line-height:1.6;"><?php echo htmlentities($resource['title']); ?></div>
					<div class="visible-content limit-height">
						<div class="inline-blk" style="width:85%"><?php echo htmlentities($resource['description']); ?></div>
					</div>
					<div style="margin-top:10px;">
						<div><?php echo $resource['time']; ?></div>
						<div><?php echo htmlentities($resource['location']) ?></div>
					</div>
				</div>
			</div>
		</div>
	</div>
 
</div>



	