<div class="user-profile-wrapper" style="width:100%;position:relative" >
	<div class="user-profile">
		<div class="cover-wrapper">
			<?php if($cover_pic !== false): ?>
				<img  style="width:100%;" src="<?php echo $cover_pic ?>">
			<?php endif; ?>
		</div>
		<div class="avator-inner-bottom" style="z-index:2;position:relative">
	<div class="avator-picture-wrapper" style="margin-top:-40px;margin-left:14px;" >
		<div class="inline-blk" style="border-radius:3px;box-shadow:1px 1px 3px #848484;margin-right:10px;width:74px;height:74px;overflow:hidden">
			<a href="<?php echo $user_page_redirect; ?>"><img  class="profile-pic" style="width:100%;min-height:100%;" src="<?php echo $profile_pic ?>"></a>
		</div>
		<div class="inline-blk fullname" style="margin:0px 0px -4px 0px;vertical-align:bottom;font-size: 15px;color: #323232;font-weight: bold;"><?php echo htmlentities($fullname); ?></div>
		<div class="summary" style=margin-top:10px;"">
			<div style="font-size:13px;" class="txt_ofl"><?php echo $education['school_name']; ?></div>
			<?php if($interest_list != ''): ?>
				<div style="font-size:13px;" class="txt_ofl">
					Interested in <?php echo htmlentities($interest_list) ?>
				</div>
			<?php endif; ?>	
		</div>
	</div>
	
	</div>
	</div>
</div>
				
 <?php if(!$activated): ?>
	 <div style="width:100%; background: #FFD466;margin-bottom:10px;border-radius:4px;border: 1px solid #EAEAEA;box-shadow: 1px 1px 10px #EAEAEA;">
		<div style="padding:20px">
			A confirmation message was sent to the email address <span style="font-weight:bold;"><?php echo htmlentities($email) ?></span>
			<div>Confirm your email address to get fully access to Higout's features</div>
		</div>
	 </div>
 <?php endif; ?>
 					