<div class="interest-side-label interest-sider-navi pointer<?php echo ($set_to_active)?' active':'' ?>" data-labelfor="<?php echo $interest_id; ?>" data-href="<?php echo $data_href; ?>" title="<?php echo htmlentities($name); ?>" >
	<div class="vertical-center"><img src="<?php echo $url; ?>"><div class="inline-blk txt_ofl<?php echo ($set_to_active)?' red-act':''; ?>" style="width:95px;margin-top:2px;"><?php echo htmlentities($name)?></div></div>
</div>
