<div class="friend-content-inner-wrapper blk" data-key="<?php echo $interest_id; ?>">
	<?php if($_SESSION['id'] == $request_user_page_id): ?>
		<div style="background:#fff; padding:10px 0px 16px 20px;">No friends in your <span class="red-act">"<?php echo htmlentities($interest_name); ?>"</span> interest group yet.	</div>
	<?php else: ?>
		<div style="background:#fff; padding:10px 0px 16px 20px;">No friends in <?php echo $request_user_page_firstname.'\'s' ?> <span class="red-act">"<?php echo htmlentities($interest_name); ?>"</span> interest group yet.</div>
	<?php endif; ?>
	
	<?php if($_SESSION['id'] == $request_user_page_id): ?>
		<div style="width: 100%;margin-top: 10px;">
			<?php
				$count = 0;
				foreach($user_found as $u){
					if($u['id'] !== $_SESSION['id']){
						if(++$count <=4){
							echo $interest->renderUserAvatorByUserResource($u);
						}
					}
				}
			?>
		</div>	
	<?php endif; ?>
</div>