<div class="initial_message" style="margin:14px;">
	<a href="<?php echo $user_page_redirect ?>"><img src="<?php echo $profile_pic; ?>" class="hover-user-profile" data-key="<?php echo $unique_iden; ?>" style="float:left;margin:0px 6px 6px 0px" height="36" width="36"></a>
	<div style="padding-bottom:10px;">
		<div class="txt_ofl" style="font-size:12px;font-weight:600;color:#3A3637"><?php echo htmlentities($fullname); ?></div>
		<div><div class="txt_ofl inline-blk" style="width:60%" >Is in your <span class="red-act pointer plain-lk">"<?php echo htmlentities($interest_name) ?>"</span> interest group</div></div>
	</div>
</div>