<div class="inline-blk" style="width:100%">
			<div style="background:#fff; padding:10px 0px 16px 20px;">You haven't added any friends yet.	<span class="plain-lk pointer suggest-message" style="
    /* padding: 0px 20px; */
">view suggest</span>	</div>
<div id="friend-content-wrapper" class="inline-blk " style="width: 90%;margin-top: 10px;">
	<?php
		foreach($user_found as $u){
			echo $this->renderUserAvatorByUserResource($u);
 		}
	?>
</div>
		
</div>