<div class="initial_message" style="margin:14px;">
	<img src="<?php echo $resource['event_photo_url']; ?>" style="float:left;margin:0px 6px 6px 0px" height="36" width="36">
	<div style="border-bottom:1px solid #f0f0f0;padding-bottom:10px;">
		<div class="txt_ofl" style="font-size:12px;font-weight:600;color:#3A3637;width:70%;" title="<?php echo htmlentities($resource['title']); ?>"><?php echo $resource['title'] ?></div>
		<div><div class="txt_ofl inline-blk" style="width:60%" title="<?php echo htmlentities($resource['location']); ?>"><?php echo $resource['location'] ?></div><div class="event-info inline-blk red-act plain-lk pointer" style="margin-left:10px;float:right">Details</div></div>
	</div>
</div>