<?php if($page_own): ?>
	<div id="add-new-interest-wrapper" class="inline-blk <?php echo (($request_user_page_has_interest)?" hdn":"") ?>" style="width:80%">
		<?php include_once 'add_new_interest_block.phtml'; ?>
	</div>
<?php endif; ?>

<div id="interest-content-wrapper" class="inline-blk <?php echo (($request_user_page_has_interest)?"":" hdn") ?>"  style="width:80%;">
	<?php echo $content; ?>
	<div class="feed-loading-wrapper hdn" style="text-align:center;margin-top:20px;"><img src="<?php echo SPINNER_ICON; ?>" height="72" width="96"></div>
</div>

<?php if(!$page_own && !$request_user_page_has_interest): ?>
	<div style="background:#fff; padding:10px 0px 16px 20px;">
		<?php
			echo $request_user_page_firstname.' hasn\'t added any interests yet '
		?>
	</div>
<?php endif; ?>


<div id="i-interest-navi" class="interest-navi inline-blk" style="text-align:left;width:18%;">
	<?php if($page_own): //allow editing ?>
		<div id="add-new-interest-navi" class="interest-sider-navi pointer<?php echo ($user_interests === false)?' hdn':'' ?> ?>" style="margin-bottom:10px;"><span class="plain-lk">Add Interest</span></div>
	<?php endif; ?>
	
	<?php if($user_interests !== false): ?>
	<?php $count = 0; ?>
	<?php foreach($user_interests as $user_interest): ?>
			<?php $count++; ?>
			<div class="interest-side-label interest-sider-navi txt_ofl pointer<?php echo ($active_interest_id == $user_interest['id'] ||  ($count == 1 && !isset($_GET['a'])))?' active':'' ?>" data-labelfor="<?php echo $user_interest['id'];?>" data-href="<?php echo $user_interest['data_href']; ?>"  title="<?php echo htmlentities($user_interest['name']);?>">
				<div class="vertical-center"><img src="<?php echo $user_interest['picture_url']; ?>"><div class="inline-blk txt_ofl<?php echo ($active_interest_id == $user_interest['id']  || ($count == 1 && !isset($_GET['a'])) ) ?' red-act':''; ?>" style="width:95px;margin-top:3px;font-size:13px;"><?php echo htmlentities($user_interest['name']);?></div></div>
			</div>	
 	<?php  endforeach;  //end display side ?>
	<?php endif ?>
</div>

