<?php
	  include_once SCRIPT_INCLUDE_BASE.'php_inc/global_constant.php'; 
?>

<div class="interest-profile post">
	<div class="interest-profile-intro sub">
		<div class="dialog-header">
			<div class="dialog-header-inner">
				<div class="inline-blk left-align dialog-header-left-item"><div class="bar-title vertical-center main-title" title="<?php echo $interest['name'] ?>"><?php echo htmlentities($interest['name']); ?></div></div>

				<div class="inline-blk right-align dialog-header-right-item">
				<?php  if($interest['user_id'] == $_SESSION['id']): ?>
					<div class="bar-title dialog-header-bar-option inline-blk pointer side-title post" style="width:34%"><div class="vertical-center" >Post</div></div>
				<?php  endif; ?>
				<div class="bar-title dialog-header-bar-option inline-blk pointer option side-title" style="width:34%"><div class="vertical-center" ><img src="<?php  echo IMGDIR ?>menu_navi_icon.png" width="20" height="13"></div></div>
				</div>
			</div>
		</div>
		<div class="dialog-body">
			<div class="visible-post-scope">
				<div class="visible-content limit-height">
					<?php if(isMediaDisplayable($interest_label_image)): ?>
						<div class="interest-image-label">
							<img src="<?php echo U_IMGDIR.$interest_label_image ?>" />
						</div>
					<?php  endif;?>
		
					<?php if(substr($interest['description'],1,1)!=' ') :?>
						<span  class="first-cap" style="position:relative;top:0px;margin-right:-3px;"><?php echo strtoupper(substr($interest['description'],0,1))?></span>
					<?php else: ?>
						<span class="first-cap" ><?php echo strtoupper(substr($interest['description'],0,1))?></span>
					<?php endif; ?>
					<span><?php echo htmlentities(substr($interest['description'],1)); ?></span>
				</div>
			</div>
		
			<div class="clr right-align exp" style="margin:0px 20px 16px 0px">
				<?php echo $experience; ?>
			</div>
			
		</div>
		
		<div class="in_con_opt_w popover" style="top:50px;right:0px;">
		<?php  if($interest['user_id'] == $_SESSION['id']): ?>
				<div class="in_con_w_opt_it edit_interest">Edit</div>
		<?php  endif; ?>	
				<div class="in_con_w_opt_it edit_interest">Interest Friends</div>
		<?php  if($interest['user_id'] == $_SESSION['id']): ?>
				<div class="in_con_w_opt_it remove_interest">Remove This Interest</div>
		<?php  endif; ?>
		</div>
		
	</div>
	
	<div class="interest-profile-edit hdn sub">
		<div class="dialog-header">
			<div class="dialog-header-inner">
				<div class="inline-blk left-align dialog-header-left-item"><div class="bar-title vertical-center" title="Guitar and Music">Edit Interest</div></div>
			</div>
		</div>
		<div class="dialog-body">

			<div style="margin:10px 10px 0px 8px;">
				<div style="position:relative">
					<label class="pointer" title="Upload a picture label for your interest">
						<div class="picture-upload-wrapper">
							<?php $hasInterestLabelImage = $interest_label_image !== false && file_exists(SCRIPT_INCLUDE_BASE.MEDIA_U.$interest_label_image); ?>
								<?php if($hasInterestLabelImage): ?>
										<img class="target-image"  src="<?php echo U_IMGDIR.$interest_label_image ?>" height="36" width="36">
								<?php else: ?>
										<img class="target-image hdn"  src="" height="36" width="36">
								<?php  endif;?>
							
								<div class="picture-upload-black-overlay"></div>
								<div class="camera-center vertical-center" ><img class="camera-icon"  src="<?php echo IMGDIR ?>camera.png"  height="18" width="18"></div>
						</div>
						<form method="POST" enctype="multipart/form-data">
							<input class="interest-picture hdn-input" data-key="<?php echo $interest['id'] ?>" data-set="false" type="file" name="picture-label" title="Upload a picture label for your interest">
						</form>
				
					</label>
	
					<div class="in-name-input-wrapper">
						<input type="text"  class="in-ed-input in-txt-n" value="<?php echo htmlentities($interest['name']); ?>" maxlength="32" placeholder="Add a name for your interest" title="add an name for your interest">
					</div>
					<textarea class="in-ed-input" style="height:80px;margin-top:3px;" placeholder="Let your friends know more about your interest, like experience, favoriate event, etc... "  title="add some descriptions about your interest"><?php echo htmlentities($interest['description']); ?>
					</textarea>
					<div style="text-align:right;padding:10px 0px">
						<select class="ep">
						
							<option data-option="-1" <?php echo (($interest['experience']==-1)?'selected':'')  ?>>Add your experience</option>
							<option data-option="0" <?php echo (($interest['experience']==0)?'selected':'')  ?>>less than 1 Year</option>
							<option data-option="1" <?php echo (($interest['experience']==1)?'selected':'')  ?>>1 Year</option>
							<?php
								for($i = 2; $i<=10; $i++){
									if($i == $interest['experience']){
										echo '<option data-option="'.$i.'" selected>'.$i.' Years</option>';
									}else{
										echo '<option data-option="'.$i.'">'.$i.' Years</option>';
									}
								}
							?>
							<option data-option="11" <?php echo (($interest['experience']==11)?'selected':'')  ?>>more than 10 years</option>
						</select>
					</div>	
					<div class="edit-dialog-footer">
							<div class="inline-blk cancel-button">Cancel</div>
						<div class="inline-blk action-button update_interest" style="margin-left:4px;">Update</div>
					</div>
					<div class="loading-icon-wrapper" style="border-radius:0px;"><div class="vertical-center" style="text-align:center;"><img class="loading-icon" src="<?php  echo IMGDIR ?>loading_icon.gif" height="40" width="40"></div></div>

				</div>
			</div>
		</div>
	
	</div>
	
	
	<div class="interest-profile-moment interest-profile-post hdn sub">
		<div class="dialog-header">
			<div class="dialog-header-inner">
				<div class="inline-blk left-align dialog-header-left-item"><div class="bar-title vertical-center" title="Guitar and Music"><?php echo htmlentities($interest['name']);  ?></div></div>
				<div class="inline-blk right-align dialog-header-right-item">
						<div class="bar-title dialog-header-bar-option inline-blk pointer" style="width:40%;"><div class="vertical-center" style="font-size:13px;">Event</div></div>
						<div class="bar-title dialog-header-bar-option inline-blk pointer" style="width:50%;background-color:#8a0000;"><div class="vertical-center" style="font-size:13px;">Moment</div></div>
				</div>
			</div>
		</div>
		<div class="dialog-body">
			<div style="margin:10px 10px 0px 8px;position:relative">
				<div style="width:100%;text-align:center;">
					<textarea class="desc" placeholder="How's your <?php echo htmlentities($interest['name']); ?> going..."></textarea>
				</div>
				<div style="border-top:1px dashed #f0f0f0;width:100%;" class="pointer center-align">
					<input class="add-date" placeholder="Add a date for this moment">
				</div>
				<div class="preview-container hdn">
					<div class="inner" style="background:#f0f0f0;">
						<div class="preview-loading-wrapper hdn" style="position:absolute;top:0px;left:0px;width:100%;height:100%;background:#fff;opacity:0.6;">
							<div class="center-align vertical-center"><img src="<?php echo IMGDIR; ?>animated-loading-bar.gif" width="22" height="22"></div>
						</div>
						<div class="target-container hdn" style="background:#fff;"><img src="" class="target-image" style="width:100%;"></div>
						<img class="cross pointer animate-opacity" src="<?php echo IMGDIR; ?>c_icon.png" title="Remove this image" />
					</div>
				</div>
			
				<div class="edit-dialog-footer" style="height:36px;">
					<label class="pointer vertical-center photo-camera" >
						<form method="POST" class="hdn-input" enctype="multipart/form-data">
							<input class="hdn-input attched-photo"  type="file" name="file">
						</form>
						<img src="<?php echo IMGDIR; ?>camera.png"title="Attach an image" height="20" width="20">
					</label>
					<div class="inline-blk cancel-button">Cancel</div>
					<div class="inline-blk action-button update_interest center-align post-moment" style="margin-left:4px;min-width:34px;">Post</div>
				</div>
				<div class="loading-icon-wrapper" style="border-radius:0px;"><div class="vertical-center" style="text-align:center;"><img class="loading-icon" src="<?php  echo IMGDIR ?>loading_icon.gif" height="50" width="50"></div></div>

			</div>
		</div>
	</div>

	
	
	
	
</div>