<!---interest page-->
<?php if($page_own): //allow editing ?>
	<div id="add-new-interest-wrapper" class="inline-blk <?php echo (($request_user_page_has_interest)?" hdn":"") ?>" style="width:80%">
	<div id="add-new-interest" class="inline-blk" style="width:58%">
		<div class="dialog-header"><div class="title">Add New Interest</div></div>
		<div class="dialog-body">
			<label class="pointer" title="Upload a picture label for your interest">
				<div class="picture-upload-wrapper">
						<img class="target-image hdn"  src="" height="36" width="36">
						<div class="picture-upload-black-overlay"></div>
						<div class="camera-center vertical-center" ><img class="camera-icon"  src="<?php echo IMGDIR ?>camera.png"  height="18" width="18"></div>
						<div class="loading-icon-wrapper"><div class="vertical-center"><img class="loading-icon" src="http://localhost:8888/lsere/media/loading_icon.gif" height="40" width="40"></div></div>

				</div>
				<form method="POST" enctype="multipart/form-data">
					<input id="new-interest-picture" class="hdn-input" type="file" name="profile-pic" title="Upload a picture label for your interest">
				</form>
				
			</label>
	
			<div class="in-name-input-wrapper">
				<input class="in-ed-input in-txt-n" type="text" maxlength="32" placeholder="Add a name for your interest" title="add an name for your interest">
			</div>
			<textarea class="in-ed-input" style="height:80px;margin-top:3px;" placeholder="Let your friends know more about your interest, like experience, favoriate event, etc... "  title="add some descriptions about your interest"></textarea>
			<div style="text-align:right;padding:10px 0px">
				<select class="ep">
					<option data-option="-1">Add your experience</option>
					<option data-option="0">less than 1 Year</option>
					<option data-option="1">1 Year</option>
					<?php
						for($i = 2; $i<=10; $i++){
							echo '<option data-option="'.$i.'">'.$i.' Years</option>';
						}
					?>
					<option data-option="11">more than 10 years</option>
				</select>
			</div>	
			<div class="edit-dialog-footer">
				<?php if($request_user_page_has_interest): ?>
					<div class="inline-blk cancel-button">Cancel</div>
				<?php endif; ?>
				<div id="add-interest" class="inline-blk action-button" style="margin-left:4px;" >Add Interest</div>
			</div>
		</div>

	</div>	
	</div>
<?php endif; ?>

<div id="interest-content-wrapper" class="inline-blk <?php echo (($request_user_page_has_interest)?"":" hdn") ?>" style="width:80%;">
	<?php echo $content; ?>
</div>


<div id="interest-navi" class="inline-blk" style="text-align:left;width:18%;">
	<?php if($page_own): //allow editing ?>
		<div id="add-new-interest-navi" class="interest-sider-navi pointer" style="margin-bottom:10px;"><span class="plain-lk">Add Interest</span></div>
	<?php endif; ?>
	
	<?php if($user_interests !== false): ?>
	<?php foreach($user_interests as $user_interest): //start display navi interests label ?>
				<div class="interest-side-label interest-sider-navi pointer" data-labelfor="<?php echo $user_interest['id'];?>" style="height:30px;margin-bottom:10px;" title="<?php echo $user_interest['name'];?>"><div class="vertical-center"><img src="<?php echo U_IMGDIR.$_USER_MEDIA_PREFIX.$user_interest['picture_url'];  ?>" style="box-shadow: 1px 1px 3px #777777;height:24px;width:24px;border-radius:50%;margin-right:6px;"><div class="inline-blk txt_ofl" style="width:95px;margin-top:2px;"><?php echo htmlentities($user_interest['name']);?></div></div></div>	
 	<?php  endforeach;  //end display side ?>
	
	
	
	
	<!-- 
<div class="interest-sider-navi pointer" style="height:30px;margin-bottom:10px;"><div class="vertical-center"><img src="http://localhost:8888/lsere/media/default_image/interest-label-1.png" style="box-shadow: 1px 1px 3px #777777;height:24px;width:24px;border-radius:50%;margin-right:6px;"><div class="inline-blk txt_ofl" style="width:95px;margin-top:2px;"><?php echo 'Hangout'?></div></div></div>	
	<div class="interest-sider-navi pointer" style="height:30px;margin-bottom:10px;"><div class="vertical-center"><img src="http://localhost:8888/lsere/media/default_image/interest-label-2.png" style="box-shadow: 1px 1px 3px #777777;height:24px;width:24px;border-radius:50%;margin-right:6px;"><div class="inline-blk txt_ofl" style="width:95px;margin-top:2px;"><?php echo 'Hangout'?></div></div></div>	
	<div class="interest-sider-navi pointer" style="height:30px;margin-bottom:10px;"><div class="vertical-center"><img src="http://localhost:8888/lsere/media/default_image/interest-label-3.png" style="box-shadow: 1px 1px 3px #777777;height:24px;width:24px;border-radius:50%;margin-right:6px;"><div class="inline-blk txt_ofl" style="width:95px;margin-top:2px;"><?php echo 'Hangout'?></div></div></div>	
	<div class="interest-sider-navi pointer" style="height:30px;margin-bottom:10px;"><div class="vertical-center"><img src="http://localhost:8888/lsere/media/default_image/interest-label-4.png" style="box-shadow: 1px 1px 3px #777777;height:24px;width:24px;border-radius:50%;margin-right:6px;"><div class="inline-blk txt_ofl" style="width:95px;margin-top:2px;"><?php echo 'Hangout'?></div></div></div>		
	<div class="interest-sider-navi pointer" style="height:30px;margin-bottom:10px;"><div class="vertical-center"><img src="http://localhost:8888/lsere/media/default_image/interest-label-5.png" style="box-shadow: 1px 1px 3px #777777;height:24px;width:24px;border-radius:50%;margin-right:6px;"><div class="inline-blk txt_ofl" style="width:95px;margin-top:2px;"><?php echo 'Hangout'?></div></div></div>	
	<div class="interest-sider-navi pointer" style="height:30px;margin-bottom:10px;"><div class="vertical-center"><img src="http://localhost:8888/lsere/media/default_image/interest-label-6.png" style="box-shadow: 1px 1px 3px #777777;height:24px;width:24px;border-radius:50%;margin-right:6px;"><div class="inline-blk txt_ofl" style="width:95px;margin-top:2px;"><?php echo 'Hangout'?></div></div></div>	
	
 -->
	<?php endif ?>
</div>

<?php if(!$page_own && !$request_user_page_has_interest): ?>
<div style="background:#fff; padding:20px;">
	<?php
		echo $request_user_page_firstname.' is so lazy that '.$request_user_page_gender_call.' hasn\'t added any interests yet '
	?>
	<span href="" class="plain-lk pointer" style="color:#062AA3">Know what <?php echo $request_user_page_gender_call ?> likes?</span>
</div>
<?php endif; ?>