<div class="list-item inline-blk pointer invitation-contact" data-key="<?php echo $unique_iden; ?>" style="height:60px;">
	<div class="user-profile" style="background:inherit">
		<div style="float:left;margin-right:10px;width:60px;height:60px;overflow:hidden;position:relative">
		<img src="<?php echo $profile_pic; ?>" class="profile-pic" style="border-radius:0px;width:100%;height:100%;">
		</div>
		<div class="inline-blk vertical-center txt_ofl name" style="font-size:13px;"><?php echo htmlentities($fullname); ?></div>
	</div>
</div>