<div style="margin: 8px 16px 10px 16px; line-height: 1.48;margin-bottom:18px;">
	<?php if($photo_url !== false && isMediaDisplayable($photo_url)): ?>
		<div class="interest-image-label">
			<img style="height:30px;width:30px;border-radius:4px" src="<?php echo U_IMGDIR.$photo_url; ?>">
		</div>
	<?php endif; ?>
	<div style="color: #525252;font-weight: bold;"><?php echo $date ?></div>
	<div class="txt_ofl"><?php echo htmlentities($description) ?></div>
</div>