<div class="list-item inline-blk" data-key="<?php echo $hash ?>">
	<a href="<?php echo $user_page_redirect; ?>"><img src="<?php echo $profile_pic ?>" class="hover-user-profile" data-key="<?php echo $unique_iden; ?>" style="float:left;margin-right:10px;width:30px;height:30px;border-radius:9%;"></a>
	<div class="inline-blk vertical-center txt_ofl" style="font-size:13px;"><?php echo htmlentities($firstname); ?></div>
</div>