<div id="login-header">
	<div id="login-header-inner">
		<div id="logo" class="gradient-red-background left-bar inline-blk">
		Higout
		</div>
		<div class="inline-blk right-bar">
			<span id="prompt-sign-up-header-top" class="pointer"><img class="right-bar-item" src="<?php echo IMGDIR ?>lock.png"  title="login" />Log in</span>
			<span id="prompt-log-in-header-top" class="pointer" ><img  id="signup-icon" class="right-bar-item" src="<?php echo IMGDIR ?>signup_icon.jpg"  title="signUp">Sign up</span>
		</div>
	</div>
</div>