<div class="in_con_opt_w" style="box-shadow:1px 1px 12px #DBDBDB;width:100%;top:40px;padding:0px;display:block;">
	<div class="in_con_opt_w_inner" style="position:relative;width:100%;margin-top:5px;">
		<div class="arrow-up" style="position:absolute;top:-14px;left:12px;border-bottom:10px solid #FFFFFF;"></div>
		<?php if($rows !== false): ?>
			<?php foreach($rows as $row): ?>	
				<div class="suggest-item major-name-item light-hover" style="height:30px;">
					<div class="text vertical-center"><?php echo $row['major_name']; ?></div>
				</div>
			<?php endforeach; ?>
		<?php endif; ?>
		</div>
	</div>
</div>