<div class="conversation other" style="text-align:left">
	<img class="sent-user-avator" style="float:left;margin:0px 8px 8px 0px;" src="<?php echo $profile_pic ?>" height="36" width="36" />
	<div class="inline-blk" style="margin-right:16px;"><?php echo htmlentities($fullname) ?></div><div  class="inline-blk" style="color:#969696"><?php echo $time; ?></div>
	<div style="margin-top:2px;color:#969696">Now is in the event</div>
</div>
