<div class="conversation other" style="text-align:left">
	<a href="<?php echo htmlentities($user_page_redirect); ?>"><img class="sent-user-avator hover-user-profile" data-key="<?php echo $unique_iden; ?>" style="float:left" src="<?php echo $profile_pic ?>" height="36" width="36" /></a>
	<div class="inline-blk text" style="margin-left:10px;">
		<!-- <div class="arrow-up" style="left:-6px;"></div> -->
		<div><?php echo htmlentities($text); ?></div>
	</div>
</div>