<div class="conversation own" style="text-align:right">
	<a href="<?php echo htmlentities($user_page_redirect); ?>"><img class="sent-user-avator" style="float:right" src="<?php echo $profile_pic ?>" height="36" width="36" /></a>
	<div class="inline-blk text" style="margin-right:10px;">
		<div class="arrow-up" style="right:-6px;"></div>
		<div><?php echo htmlentities($text); ?></div>
	</div>
</div>