<div class="post-wrapper post evt-block passed-evt-block" data-key="<?php echo $hash; ?>">


	<?php $displayable = isMediaDisplayable($event_photo); ?>

	<?php if($displayable): ?>
		<img src="<?php echo IMGDIR ?>menu_navi_icon.png" style="float:none;position: absolute; right: 10px; top: 14px;width:20px;height:14px;"class="toggle-operation pointer hdn">

		<div class="pointer evt-photo-wrap" style="max-height:300px;overflow:hidden;background:#f0f0f0;position:relative;" title="View Photos in This Event">
			<img style="max-width:100%;" src="<?php echo U_IMGDIR.$event_photo ?>">
			<div style="position:absolute;bottom:6px;right:0px;">
				<div style="color:#fff;padding:10px;background:#000;font-size:13px;">2 Photos</div>
			</div>
		</div>
	<?php else: ?>
			<img src="<?php echo IMGDIR ?>menu_navi_icon.png" style="float:none;position: absolute; right: 10px; top: 10px;"class="toggle-operation pointer hdn">
	<?php endif; ?>
	
	
	

	<div class="content">
		<div class="post-text" style="margin-top:30px;padding:0px 18px;">
			<div class="visible-post-scope">
				<div class="title" style="color:rgb(114, 113, 113);font-size:20px;"><?php echo $title; ?></div>
				<div class="visible-content limit-height">
					<div class="desc"><?php echo $description; ?></div>
				</div>
				<div class="evt-info-wrapper">
					<div style="font-weight:bold;font-size:15px;color:rgb(114, 113, 113);text-align:center"><?php echo $date; ?></div>
				</div>
			</div>
		</div>
		
		
		<div class="post-inner-padding" style="padding-top:0px">
			<div class="inline-blk" style="vertical-align:bottom"><img class="post-operation-icon pointer toggle-slide-comment" src="<?php echo IMGDIR ?>ci.png" title="Comment" height="16" width="16"><div class="inline-blk cmt-num" style="margin:-3px 8px 0px 0px"><?php echo $comment_number ?></div></div>
			<div class="inline-blk" style="vertical-align:bottom"><img class="post-operation-icon pointer" src="<?php echo IMGDIR ?>favor_icon.png" title="Pin" height="18" width="18"><div class="inline-blk" style="margin-top:-1px;"></div></div>
			<div class=
			"inline-blk pointer" style="float:right;vertical-align:bottom"><img class="e_w_b_1_c_1_a" src="<?php echo IMGDIR ?>location_icon.png" height="17" width="17" title="Event Location"></div>
		</div>
	
		<div class="post-inner-padding comment-block" style="padding-top:0px">
			<div class="regular-comment-wrapper hdn">
				<textarea class="fcy-txt comment-txt" placeholder="Write down your thoughts..." data-key="<?php echo $hash; ?>"></textarea>
				<div class="comment-container" style="margin-top:20px;">
				
				</div>
			</div>
 			<div class="slideshow-comment-wrapper" style="overflow:hidden;height:56px;position:relative;">
 				<?php echo $comment_block; ?>
 			</div>
		</div>
	</div>
	
	
	<div class="in_con_opt_w popover" style="top:34px;right:12px;">
		<div class="in_con_w_opt_it">Photos</div>
		<div class="in_con_w_opt_it">Friends</div>
		<div class="in_con_w_opt_it remove_activity">Remove This Post</div>
	</div>
</div>
