<?php if($content !== false): ?>
	<div id="photo-content-wrapper">
		<div class="photo-content-left inline-blk" style="width: 46%;margin-left:6px;">
			<?php echo $left_content; ?>
		</div>
		<div class="photo-content-right inline-blk" style="width: 46%;margin-left:2px;">
			<?php echo $right_content; ?>
		</div>
		<div class="feed-loading-wrapper hdn" style="text-align:center;margin-top:20px;"><img src="<?php echo SPINNER_ICON; ?>" height="72" width="96"></div>
	</div>
<?php else: ?>
	<?php if($user_id == $_SESSION['id']): ?>
		<div style="background:#fff; padding:10px 0px 16px 20px;">You haven't added any photos yet. <a href="<?php echo SEARCH_MINE_PHOTO_PATH; ?>" class="plain-lk pointer suggest-message">view suggest</a>	</div>
	<?php else: ?>
		<div style="background:#fff; padding:10px 0px 16px 20px;"><?php echo  htmlentities($firstname) ?> hasn't added any photos yet. </div>
	<?php endif;?>
<?php endif; ?>
 
