<div class="popover-child interest-request" data-key="<?php echo $hash; ?>" >
	<a href="<?php echo $user_page_redirect ?>"><img src="<?php  echo $sender_pic ?>" class="sender-avator" ></a>
	<div class="inner">
		<div class="inner-container">
			<div class="inline-blk txt_ofl" style="max-width:50%;margin-bottom:2px;"><a class="profile-name plain-lk normal-font"  href="<?php echo $user_page_redirect ?>"><?php echo htmlentities($fullname); ?></a></div><span class="react" style="margin-left:4px;font-size:12px;"><?php echo $sent_time ?></span>
			
			<?php if($isRequestIgnored): ?>
				<div class="inline-blk" style="float:right;font-size:13px;">
					<span style="margin-right:4px;">Ignored</span>
				</div>
			<?php elseif($isRequestAccepted): ?>
				<div class="inline-blk" style="float:right;font-size:13px;">
					<span style="margin-right:4px;">Accepted</span>
				</div>
			<?php else: ?>
				<div class="inline-blk option" style="float:right;font-size:13px;">
					<span class="plain-lk pointer animate-opacity accept" style="margin-right:4px;">Accept</span>
					<span class="plain-lk pointer animate-opacity ignore" style="margin:0px 4px 0px 6px;">Ignore</span>
				</div>	
			<?php endif; ?>
			
			
			
			
			
			<div style="font-size:12px;color:rgb(137, 137, 137)">Wants to connect you to <?php echo $herorhis ?> 
				<a class="plain-lk target" title="<?php echo htmlentities($interest_description) ?>">"<?php echo htmlentities($interest_name); ?>"</a> interest group
			</div>
			
		</div>
	</div>

</div>