<div class="comment cmt" data-key="<?php echo $hash; ?>" style="margin-bottom: 10px;padding: 10px 0px;">
	<a href="<?php echo $user_page_redirect ?>"><img src="<?php  echo $post_owner_pic ?>" class="comment-from-picture"></a>
	
	<div class="inner">
		<div class="inner-container">
			<div class="visible-post-scope">
				<div class="visible-content limit-height">
				<a class="profile-name plain-lk normal-font"  href="<?php echo $user_page_redirect ?>"><?php echo htmlentities($fullname); ?>:</a>
				<span class="noti-text"><?php echo htmlentities($text) ?></span>
				
				
			<?php if($isReply !== false): ?> 
				<span class="popover-throwable">
					<img src="<?php echo IMGDIR ?>plane_sent_icon.png" class="request-sent" style="margin-left:3px;opacity:0.4;"  title="Reply Sent">
				</span>
 			<?php  endif;?>

				</div>
			</div>
			<div style="position:relative;top:2px;left:-2px;font-size:12px;">
				<div class="txt_ofl"><span style="opacity:0.7;">Commented on your post "<a href="" class="plain-lk"><?php echo htmlentities($post_text) ?></a>"</span></div>

				<span class="react"><?php echo $post_time ?></span>
				<?php if($user_id != $_SESSION['id']): ?>
					<span class="reply-comment react pointer">Reply</span>
				<?php endif; ?>
				<img src="<?php echo IMGDIR ?>thumb_icon.png" class="thumb" title="like" height="14" width="14"> <span></span>
				<?php if($user_id == $_SESSION['id'] || $post_owner_id == $_SESSION['id']): ?>
					<img src="<?php echo IMGDIR ?>trashcan_icon.png" class="react pointer trash-comment trashcan hdn"  height="14" width="14" title="delete this comment">
				<?php  endif; ?>
			</div>
		</div>
		<?php if($user_id != $_SESSION['id']): ?>
			<textarea class="fcy-txt noti-comment-reply hdn" style="margin-top:12px;" data-key="<?php echo $hash; ?>" placeholder="Reply to <?php echo $fullname ?>..."></textarea>
		<?php endif; ?>
		
	</div>
	
</div>



