<div class="popover-child interest-request" data-key="<?php echo $hash; ?>">  
	<a href="<?php echo $user_page_redirect; ?>"><img src="<?php echo $profile_pic; ?>" class="sender-avator hover-user-profile" data-key="<?php echo $unique_iden ?>"></a>
	<div class="inner">
		<div class="inner-container">
			<div class="inline-blk txt_ofl" style="max-width:50%;margin-bottom:2px;"><a  href="<?php echo $user_page_redirect; ?>" class="profile-name plain-lk normal-font hover-user-profile" data-key="<?php echo $unique_iden ?>"><?php echo htmlentities($fullname) ?></a></div><span class="react" style="margin-left:4px;font-size:12px;"><?php echo $time; ?></span>
			<div style="position:relative;top:2px;left:-2px;font-size:12px;">
				<div class="txt_ofl" title="<?php echo ($comment !== false)?htmlentities($comment):'The post might have been deleted or is not available to display'; ?>" style="margin-bottom:3px;"><span style="opacity:0.8;">Favored your comment
				 <?php if($comment !== false): ?>
					 <span class="target plain-lk">"<?php echo htmlentities($comment) ?>"</span>
				 <?php else: ?>
				 	 <span class="plain-lk">"<?php echo 'The comment might have been deleted or is not available to display' ?>"</span>
				<?php  endif; ?>
				 </span></div>
			</div>
		</div>
	</div>
</div>