<div class="popover-child event-include-request" data-key="<?php echo $hash; ?>" >
	<a href="<?php echo $user_page_redirect ?>"><img src="<?php  echo $sender_pic ?>" class="sender-avator hover-user-profile" data-key="<?php echo $unique_iden ?>" ></a>
	<div class="inner">
		<div class="inner-container">
			<div class="inline-blk txt_ofl" style="max-width:50%;margin-bottom:2px;"><a href="<?php echo $user_page_redirect ?>" class="profile-name plain-lk normal-font hover-user-profile" data-key="<?php echo $unique_iden ?>"><?php echo htmlentities($fullname); ?></a></div><span class="react" style="margin-left:4px;font-size:12px;"><?php echo $sent_time ?></span>
			
			<?php if($isRequestIgnored): ?>
				<div class="inline-blk" style="float:right;font-size:13px;">
					<span style="margin-right:4px;">Ignored</span>
				</div>
			<?php elseif($isRequestAccepted): ?>
				<div class="inline-blk" style="float:right;font-size:13px;">
					<span style="margin-right:4px;">Accepted</span>
				</div>
			<?php else: ?>
				<div class="inline-blk option" style="float:right;font-size:13px;">
					<span class="plain-lk pointer accept" style="margin-right:4px;">Accept</span>
					<span class="plain-lk pointer ignore" style="margin:0px 4px 0px 6px;">Ignore</span>
				</div>	
			<?php endif; ?>
			
			
			
			
			
			<div style="font-size:12px;color:rgb(137, 137, 137)">Wanted to include you in <?php echo $pronoun ?> event
				<span class="plain-lk target" title="<?php echo htmlentities($event_title) ?>">"<?php echo htmlentities($event_title) ?>"</span>
			</div>
			
		</div>
	</div>

</div>