<div class="popover-child interest-request" data-key="<?php echo $hash; ?>" >
	<a href="<?php echo $user_page_redirect ?>"><img src="<?php  echo $sender_pic ?>" class="sender-avator" ></a>
	<div class="inner">
		<div class="inner-container">
			<div class="inline-blk txt_ofl" style="max-width:50%;margin-bottom:2px;"><a class="profile-name plain-lk normal-font"  href="<?php echo $user_page_redirect ?>"><?php echo htmlentities($fullname); ?></a></div><span class="react" style="margin-left:4px;font-size:12px;"><?php echo $sent_time ?></span>
			<div style="font-size:12px;color:rgb(137, 137, 137)">Now is in your 
				<a class="plain-lk target" title="<?php echo htmlentities($interest_description) ?>">"<?php echo htmlentities($interest_name); ?>"</a> interest group
			</div>
			
		</div>
	</div>

</div>