<div class="post-wrapper post evt-block" data-key="<?php echo $hash; ?>">
	
	

<div class="joined-list hdn" style="z-index:1;text-align:left;position:relative">
		<div class="dialog-header" style="width:100%;">
			<div class="dialog-header-inner" style="margin:0px;">
				<div class="txt_ofl" style="color:#fff;padding:10px 13px;font-weight:600;"><?php echo htmlentities($title); ?></div>
			</div>
		</div>
		<div style="margin:10px auto;width:90%;position:relative;">
			<div style="margin-bottom:10px;">4 people are going</div>
			<div class="list-item inline-blk">
				<img src="http://localhost:8888/lsere/media_u/597394f9fe626bbb1f13c37f/4358d1f8e26a23e87ad92964/thumb_6e90cee991f25c6c904eabbb.jpg" style="float:left;margin-right:10px;width:30px;height:30px;border-radius:9%;">
				<div class="inline-blk vertical-center txt_ofl" style="font-size:13px;">Nicholas</div>
			</div>
			<div class="list-item inline-blk">
				<img src="http://localhost:8888/lsere/media_u/0b6b58a7d212e078ed4662cb/406867654e08b646857e431d/thumb_be08ebe9354ca99c168b0976.jpg" style="float:left;margin-right:10px;width:30px;height:30px;border-radius:9%;">
				<div class="inline-blk vertical-center txt_ofl" style="font-size:13px;">Meghan</div>
			</div>

			<div class="list-item inline-blk">
				<img src="http://localhost:8888/lsere/media_u/48115f24e89820aede4825d6/10059e85d3306094df94bb21/thumb_c403cf558ee807a776c20963.jpg" style="float:left;margin-right:10px;width:30px;height:30px;border-radius:9%;">
				<div class="inline-blk vertical-center txt_ofl" style="font-size:13px;">Quentin</div>
			</div>

			<div class="list-item inline-blk">
				<img src="http://localhost:8888/lsere/media_u/06f1e47fbdb03e48203ebfba/eac5b69845c56a5ad39933bd/thumb_443fae5d7fc18ce21b89c814.jpg" style="float:left;margin-right:10px;width:30px;height:30px;border-radius:9%;">
				<div class="inline-blk vertical-center txt_ofl" style="font-size:13px;">Kesong</div>
			</div>
		</div>
		
		<div class="hdn" style="border-top:1px solid #EAEAEA;width:100%;clear:both;position:absolute;bottom:0px;">
			<input type="text" style="margin:0px auto;border:0px;width:90%;padding:6px 12px;" placeholder="invite friends who might be interested" />
		</div>
			
			
		
	</div>

	

	<?php $displayable = is_url_exist($event_photo_url); ?>

	<?php if($displayable): ?>
		<img src="<?php echo IMGDIR ?>white-down-arrow.png" style="float:none;position: absolute; right: 14px; top: 14px;"class="toggle-operation pointer hdn">
		<div class="pointer" style="max-height:200px;overflow:hidden;background:#f0f0f0">
			<img class="previewable" style="width:100%;display:block;" src="<?php echo $event_photo_url ?>" data-key="<?php echo $event_photo_hash ?>" data-sourceFrom = "e">
		</div>
	<?php else: ?>
			<img src="<?php echo IMGDIR ?>down_arrow_icon.png" style="float:none;position: absolute; right: 10px; top: 10px;"class="toggle-operation pointer hdn">
			
	<?php endif; ?>
	
	<?php if($displayable): ?>
		<div style="padding:0px 14px 0px 14px; margin-top:-22px;">
	<?php else: ?>
		<div style="padding:20px 14px 0px 14px" ?>
	<?php endif ?>
			
			<div class="inline-blk"><a href="<?php echo $user_page_redirect; ?>"><img class="post-owner-picture" style="float:none;width:50px;height:50px"src="<?php echo $post_owner_pic; ?>"></a></div>
			<?php if($displayable): ?>
			<div class="inline-blk" style="vertical-align:bottom;padding-bottom:4px;">
			<?php  else:?>
			<div class="inline-blk" style="vertical-align:top;padding-bottom:4px;">
			<?php endif ?>
			
			<a class="plain-lk"  href="<?php echo $user_page_redirect; ?>">
				<span class="profile-name pointer post-user-name"><?php echo htmlentities($fullname) ?></span>
			</a>
			
			<?php if($displayable): ?>
			<span style="margin-left: 10px; color: #969696;"><?php echo $post_time ?></span>
			<?php  else:?>
			<div style="color: #969696;"><?php echo $post_time ?></div>
			<?php endif ?>
		</div>

	</div>	
	
	

	<div class="content">
		<div class="post-text" style="margin-top:30px">
			<div class="visible-post-scope">
				<div class="title"  style="margin:20px;"><?php echo $title; ?></div>
				<div class="visible-content limit-height">
					<div class="desc" style="padding:0px 20px;"><?php echo $description; ?></div>
				</div>
				<div class="evt-info-wrapper" style="margin-top:20px;">
					<div class="evt-info"><?php echo $time; ?></div>
					<div class="evt-info"><?php echo htmlentities($location) ?></div>
					<div class="evt-info" style="position:relative;margin:0px;">
						<div class="inline-blk  plain-lk pointer joined-user-info">
							<div class="joined-num inline-blk" ><?php  echo $joined_user_num; ?></div>
							<div class="joined-label inline-blk" >
							<?php if($joined_user_num > 1): ?>
								people going
							<?php else: ?>
								person going							
							<?php endif; ?>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		
		<div style="text-align:center; margin-bottom:10px;padding:30px;">
		<?php if(!$isEventPassed): ?>
			<?php  if($interest_activity['user_id'] != $_SESSION['id']): ?>
				<?php if($event_joined): ?>
					<div class="evt-action-button inline-blk evt-joined">Joined</div>
				<?php else: ?>
					<div class="evt-action-button inline-blk evt-join">Join</div>
				<?php endif; ?>
			<?php endif ?>
		<?php endif;?>
 		</div>
		
		<div class="post-inner-padding" style="padding-top:0px">
			<div class="inline-blk" style="vertical-align:bottom"><img class="post-operation-icon pointer toggle-comment" src="<?php echo IMGDIR ?>ci.png" title="Comment" height="16" width="16"><div class="inline-blk cmt-num" style="margin:-3px 8px 0px 0px"><?php echo $comment_number ?></div></div>
			<div class="inline-blk" style="vertical-align:bottom"><img class="post-operation-icon pointer" src="<?php echo IMGDIR ?>favor_icon.png" title="Pin" height="18" width="18"><div class="inline-blk" style="margin-top:-1px;"></div></div>
		</div>
		
		<div class="post-inner-padding regular-comment-wrapper comment-block hdn" style="padding-top:0px">
			<textarea class="fcy-txt comment-txt" style="margin-top:12px;" placeholder="Write down your thoughts..." data-key="<?php echo $hash; ?>"></textarea>
			<div class="comment-container" style="margin-top:20px;">
			</div>
		</div>
	</div>
	
	<div class="in_con_opt_w popover" style="top:37px;right:4px;">
		<div class="in_con_opt_w_inner" style="position:relative;width:100%;">
			<div class="arrow-up" style="position:absolute;top:-12px;right:1px;border-bottom:10px solid #FFFFFF"></div>
			<?php  if($interest_activity['user_id'] == $_SESSION['id']): ?>
			<div class="in_con_w_opt_it remove_activity">Remove This Post</div>
			<?php endif; ?>
		</div>
	</div>
	
	
	
	
	
	
	
	
	
	
</div>

