<div class="post-wrapper post evt-block evt" data-key="<?php echo $hash; ?>">
	<?php $displayable = $event_photo && is_url_exist($event_photo_url); ?>
		<?php if($operation_dispable): ?>
			<img src="<?php echo IMGDIR ?>white-down-arrow.png" style="float:none;position: absolute; right: 14px; top: 14px;z-index:1"class="trigger-pop toggle-operation pointer hdn">
		<?php endif; ?>
		
		<div class="evt-cover slide-up-blk-trigger<?php echo ($displayable)?' pointer':'' ?>">
			<?php if($displayable): ?>
				<img class="previewable" style="width:100%;display:block;" src="<?php echo $event_photo_url ?>" data-key="<?php echo $event_photo_hash ?>" data-sourceFrom = "e">
			<?php else:; ?>
			<img class="temp-preview hdn" style="width:100%;display:block;" >
			<label for="upload-cover-<?php echo $hash ?>"  class="pointer slide-up-blk" title="upload cover photo">Add Cover</label>
				<form method="POST" style="display:none" enctype="multipart/form-data">
					<input id="upload-cover-<?php echo $hash ?>" class="event-upload-cover hdn-input" type="file" name="profile-pic" title="upload cover photo">
				</form>
			<div class="overlay hdn wht-loading-overlay" style="z-index:1"><div class="vertical-center"><img class="loading-icon" style="width:60px;height:40px;" src="<?php echo IMGDIR; ?>loading_icon.gif"></div></div>
			<?php endif; ?>				
		</div>
	
		<div style="padding:0px 14px 0px 14px; margin-top:-22px;">
			<div class="inline-blk" style="position:relative;z-index:2;"><a href="<?php echo $user_page_redirect; ?>" ><img class="post-owner-picture hover-user-profile"  data-key="<?php echo $unique_iden; ?>" style="float:none;width:50px;height:50px"src="<?php echo $post_owner_pic; ?>"></a></div>
			<div class="inline-blk" style="vertical-align:bottom;padding-bottom:4px;">
			
			<a href="<?php echo $user_page_redirect; ?>" class="hover-user-profile plain-lk"  data-key="<?php echo $unique_iden; ?>">
				<span class="profile-name pointer post-user-name"><?php echo htmlentities($fullname) ?></span>
			</a>
			
			<span style="margin-left: 10px; color: #969696;">
			<?php if($with_interest_name): ?>
				<a class="plain-lk" style="color:inherit" href="<?php echo $interest_access_url; ?>"><?php echo htmlentities($interest_name); ?></a>
				-
			<?php endif; ?>
			<?php echo $post_time ?></span>
		</div>
	</div>	
	
	<div class="content">
		<div class="post-text" style="margin-top:30px">
			<div class="visible-post-scope">
				<div class="title"  style="margin:20px;"><?php echo $title; ?></div>
				<div class="visible-content limit-height">
					<div class="desc" style="padding:0px 20px;"><?php echo $description; ?></div>
				</div>
				<div class="evt-info-wrapper" style="margin-top:20px;">
					<div class="evt-info"><?php echo $time; ?></div>
					<div class="evt-info"><?php echo htmlentities($location) ?></div>
					<div class="evt-info" style="position:relative;margin:0px;">
						<div class="inline-blk  plain-lk pointer joined-user-info toggle-joined">
							<div class="joined-num inline-blk" ><?php  echo $joined_user_num; ?></div>
							<div class="joined-label inline-blk" >
							<?php if($joined_user_num > 1): ?>
								people 
							<?php else: ?>
								person
							<?php endif; ?>
							
							<?php if($isEventPassed): ?>
								went
							<?php else: ?>
								going
							<?php endif; ?>
							
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		
		<div style="text-align:center; margin-bottom:10px;padding:30px;">
		<?php if(!$isEventPassed): ?>
			<?php  if($interest_activity['user_id'] != $_SESSION['id']): ?>
				<?php if($event_joined): ?>
					<div class="evt-action-button inline-blk evt-joined">Joined</div>
				<?php else: ?>
					<div class="evt-action-button inline-blk evt-join">Join</div>
				<?php endif; ?>
			<?php endif ?>
		<?php endif;?>
 		</div>
		
		<div class="post-inner-padding" style="padding-top:0px">
			<div class="inline-blk" ><img class="post-operation-icon pointer toggle-comment" src="<?php echo IMGDIR ?>ci.png" title="Comment" height="16" width="16"><div class="cmt-num inline-blk action-num" style="margin:-3px 8px 0px 0px"><?php echo $comment_number ?></div></div>
			<div class="inline-blk" style="margin-top:-3px;"><img class="post-operation-icon pointer toggle-joined t-j" src="<?php echo IMGDIR ?>profile-icon.png" title="People Joined" height="18" width="18"><div class="inline-blk joined-num action-num"  style="margin:0px 8px 0px 0px"><?php echo $joined_user_num; ?></div></div>
		</div>
		
<div class="joined-list list hdn">
	<div class="joined-list-inner list-inner" >
	</div>
</div>	


		<div class="post-inner-padding regular-comment-wrapper comment-block hdn" style="padding-top:0px">
			<textarea class="fcy-txt comment-txt" style="margin-top:12px;" data-key="<?php echo $hash; ?>"></textarea>
			<div class="comment-container" style="margin-top:20px;">
			</div>
		</div>
	</div>
	
	<?php if($operation_dispable): ?>
	<div class="in_con_opt_w popover hdn" style="top:37px;right:4px;">
		<div class="in_con_opt_w_inner" style="position:relative;width:100%;">
			<div class="arrow-up" style="position:absolute;top:-12px;right:6px;border-bottom:10px solid #FFFFFF"></div>
			<?php //for those who have joined the event are able to upload the photos ?>
				<!-- <div class="group-contact in_con_w_opt_it" data-key="<?php echo $group_key; ?>">Photo Collection</div> -->
				<?php  if($interest_activity['user_id'] == $_SESSION['id']): ?>
					<?php if($isEventPassed): ?>
						<div class="in_con_w_opt_it include-friend" title="Who else was in the event">Include Friends</div>
					<?php else: ?>
						<div class="in_con_w_opt_it invite-friend">Invite Friends</div>
					<?php endif; ?>
			<?php endif; ?>
			<?php if($group_key !== false): ?>
				<div class="group-contact in_con_w_opt_it" data-key="<?php echo $group_key; ?>">Group Message</div>
			<?php endif; ?>
			<?php  if($interest_activity['user_id'] == $_SESSION['id']): ?>
			<div class="in_con_w_opt_it remove_activity">Remove This Post</div>
			<?php endif; ?>
		</div>
	</div>
	<?php endif;?>
</div>

