<div class="post-wrapper post" style="padding:0px;" data-key="<?php echo $hash ?>">
	<div style="padding:16px 14px 0px 14px;"><a href="<?php echo $user_page_redirect; ?>"><img class="post-owner-picture" src="<?php echo $post_owner_pic; ?>"></a>
	<a class="plain-lk" href="<?php echo $user_page_redirect; ?>"><span class="profile-name pointer post-user-name"><?php echo htmlentities($fullname) ?></span></a>
	<img src="<?php echo IMGDIR ?>down_arrow_icon.png" class="toggle-operation pointer hdn">
	<div style="margin-left: 10px; color: #969696;"><?php echo $post_time ?></div>
	</div>
	<div class="content">
		<div style="padding:0px 18px;">
		<div class="post-text">
			<div class="visible-post-scope">
				<div class="visible-content limit-height">
					<span><?php  echo htmlentities($description); ?></span>
				</div>
			</div>
		</div>
		<div class="moment-date">
			<?php echo $date ?>
		</div>
		</div>
		<div style="margin-top:10px;">
			<?php if(isMediaDisplayable($moment_photo)): ?>
			<img style="width:100%;" src="<?php echo U_IMGDIR.$moment_photo ?>">
			<?php if($caption !== false && $caption !== null && !empty($caption)):?>
			<div style="text-align:right;margin-right:10px;"><span title="<?php echo htmlentities($caption); ?>" style="opacity:0.6;font-size:13px"><?php echo ((strlen($caption)>30)?substr($caption,0,30).'...':$caption) ?><span></div>
			<?php endif;?>
			<?php endif; ?>
		</div>
		
		<div style="margin: 12px 18px;">
			<div style="margin-top:10px">
				<div class="inline-blk" style="vertical-align:bottom"><img class="post-operation-icon pointer toggle-comment" src="<?php echo IMGDIR ?>ci.png"  title="Comment" height="16" width="16" ><div class="inline-blk cmt-num" style="margin:-3px 8px 0px 0px"><?php echo $comment_number; ?></div></div>
				<div class="inline-blk" style="vertical-align:bottom"><img class="post-operation-icon pointer" src="<?php echo IMGDIR ?>favor_icon.png"  title="Pin" height="18" width="18"><div class="inline-blk" style="margin-top:-1px;"></div></div>
			</div>
			<div class="comment-block hdn">
				<textarea class="fcy-txt comment-txt" placeholder="Write down your thoughts..." data-key="<?php echo $hash ?>"></textarea>
				<div class="comment-container" style="margin-top:20px;">
				
				</div>
			</div>
		</div>
		
		
	</div>
	
	
	<div class="in_con_opt_w popover" style="top:34px;right:12px;">
		<?php  if($interest_activity['user_id'] == $_SESSION['id']): ?>
			<div class="in_con_w_opt_it remove_activity">Remove This Moment</div>
		<?php  endif;?>
		<?php  if($interest_activity['user_id'] != $_SESSION['id']): ?>
			<div class="in_con_w_opt_it remove_activity">Block this Post</div>
		<?php endif; ?>
	</div>
</div>
		