<div class="post-wrapper post">
	<a href="#"><img class="post-owner-picture" src="<?php echo $post_owner_pic; ?>"></a>
	<a class="plain-lk" href="#"><span class="profile-name pointer"><?php echo htmlentities($fullname) ?></span></a>
	<img src="<?php echo IMGDIR ?>down_arrow_icon.png" class="toggle-operation pointer hdn">
	<div style="margin-left: 10px; color: #969696;"><?php echo $post_time ?></div>
	<div class="content">
		<div class="post-text">
			<div class="visible-post-scope">
				<div class="visible-content limit-height">
					<span><?php  echo htmlentities($description); ?></span>
				</div>
			</div>
		</div>
		<div class="moment-date">
			<?php echo $date ?>
		</div>
		<div style="margin-top:10px;">
			<?php if(isMediaDisplayable($moment_photo)): ?>
			<img style="max-width:100%;" src="<?php echo U_IMGDIR.$moment_photo ?>">
			<?php endif; ?>
		</div>
		
		
		<div style="margin-top:10px">
			<div class="inline-blk" style="vertical-align:bottom"><img class="post-operation-icon pointer toggle-comment" src="<?php echo IMGDIR ?>ci.png"  title="Comment" height="16" width="16" ><div class="inline-blk" style="margin-top:-3px;"></div></div>
			<div class="inline-blk" style="vertical-align:bottom"><img class="post-operation-icon pointer" src="<?php echo IMGDIR ?>favor_icon.png"  title="Pin" height="18" width="18"><div class="inline-blk" style="margin-top:-1px;"></div></div>
		</div>
		<div class="comment-block hdn">
			<textarea class="fcy_txt" placeholder="Write down your thoughts..."></textarea>
		</div>
	</div>
	
	
	<div class="in_con_opt_w popover" style="top:34px;right:12px;">
		<div class="in_con_w_opt_it remove_interest">Remove This Moment</div>
	</div>
</div>
		