<div class="post-wrapper post evt-block evt" data-key="<?php echo $hash; ?>">
	<?php $displayable = is_url_exist($event_photo_url); ?>

	<?php if($displayable): ?>
		<?php if($operation_dispable): ?>
		<img src="<?php echo IMGDIR ?>white-down-arrow.png" style="float:none;position: absolute; right: 14px; top: 14px;"class="trigger-pop toggle-operation pointer hdn">
		<?php endif; ?>
		
		<div class="pointer evt-cover">
			<img class="previewable" style="width:100%;display:block;" src="<?php echo $event_photo_url ?>" data-key="<?php echo $event_photo_hash ?>" data-sourceFrom = "e">
		</div>
	<?php else: ?>
		<?php if($operation_dispable): ?>
			<img src="<?php echo IMGDIR ?>down_arrow_icon.png" style="float:none;position: absolute; right: 10px; top: 10px;"class="trigger-pop toggle-operation pointer hdn">
		<?php endif; ?>
	<?php endif; ?>
	
	<?php if($displayable): ?>
		<div style="padding:0px 14px 0px 14px; margin-top:-22px;">
	<?php else: ?>
		<div style="padding:20px 14px 0px 14px" ?>
	<?php endif ?>
			
			<div class="inline-blk"><a href="<?php echo $user_page_redirect; ?>"  class="hover-user-profile"  data-key="<?php echo $unique_iden; ?>"><img class="post-owner-picture" style="float:none;width:50px;height:50px"src="<?php echo $post_owner_pic; ?>"></a></div>
			<?php if($displayable): ?>
			<div class="inline-blk" style="vertical-align:bottom;padding-bottom:4px;">
			<?php  else:?>
			<div class="inline-blk" style="vertical-align:top;padding-bottom:4px;">
			<?php endif ?>
			
			<a href="<?php echo $user_page_redirect; ?>" class="hover-user-profile plain-lk"  data-key="<?php echo $unique_iden; ?>">
				<span class="profile-name pointer post-user-name"><?php echo htmlentities($fullname) ?></span>
			</a>
			
			<?php if($displayable): ?>
			<span style="margin-left: 10px; color: #969696;"><?php echo $post_time ?></span>
			<?php  else:?>
			<div style="color: #969696;"><?php echo $post_time ?></div>
			<?php endif ?>
		</div>

	</div>	
	
	

	<div class="content">
		<div class="post-text" style="margin-top:30px">
			<div class="visible-post-scope">
				<div class="title"  style="margin:20px;"><?php echo $title; ?></div>
				<div class="visible-content limit-height">
					<div class="desc" style="padding:0px 20px;"><?php echo $description; ?></div>
				</div>
				<div class="evt-info-wrapper" style="margin-top:20px;">
					<div class="evt-info"><?php echo $time; ?></div>
					<div class="evt-info"><?php echo htmlentities($location) ?></div>
					<div class="evt-info" style="position:relative;margin:0px;">
						<div class="inline-blk  plain-lk pointer joined-user-info toggle-joined">
							<div class="joined-num inline-blk" ><?php  echo $joined_user_num; ?></div>
							<div class="joined-label inline-blk" >
							<?php if($joined_user_num > 1): ?>
								people 
							<?php else: ?>
								person
							<?php endif; ?>
							
							<?php if($isEventPassed): ?>
								went
							<?php else: ?>
								going
							<?php endif; ?>
							
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		
		<div style="text-align:center; margin-bottom:10px;padding:30px;">
		<?php if(!$isEventPassed): ?>
			<?php  if($interest_activity['user_id'] != $_SESSION['id']): ?>
				<?php if($event_joined): ?>
					<div class="evt-action-button inline-blk evt-joined">Joined</div>
				<?php else: ?>
					<div class="evt-action-button inline-blk evt-join">Join</div>
				<?php endif; ?>
			<?php endif ?>
		<?php endif;?>
 		</div>
		
		<div class="post-inner-padding" style="padding-top:0px">
			<div class="inline-blk" ><img class="post-operation-icon pointer toggle-comment" src="<?php echo IMGDIR ?>ci.png" title="Comment" height="16" width="16"><div class="cmt-num inline-blk" style="margin:-3px 8px 0px 0px"><?php echo $comment_number ?></div></div>
			<div class="inline-blk" style="margin-top:-3px;"><img class="post-operation-icon pointer toggle-joined t-j" src="<?php echo IMGDIR ?>profile-icon.png" title="People joined" height="18" width="18"><div class="inline-blk joined-num"  style="margin:0px 8px 0px 0px"><?php echo $joined_user_num; ?></div></div>
		</div>
		
		
		
			

<div class="joined-list list hdn">
	<div class="joined-list-inner list-inner" >
			
	</div>
</div>	


		<div class="post-inner-padding regular-comment-wrapper comment-block hdn" style="padding-top:0px">
			<textarea class="fcy-txt comment-txt" style="margin-top:12px;" data-key="<?php echo $hash; ?>"></textarea>
			<div class="comment-container" style="margin-top:20px;">
			</div>
		</div>
	</div>
	
	
	
	<?php if($operation_dispable): ?>
	<div class="in_con_opt_w popover hdn" style="top:37px;right:4px;">
		<div class="in_con_opt_w_inner" style="position:relative;width:100%;">
			<div class="arrow-up" style="position:absolute;top:-12px;right:1px;border-bottom:10px solid #FFFFFF"></div>
			<?php //for those who have joined the event are able to upload the photos ?>
				<!-- <div class="group-contact in_con_w_opt_it" data-key="<?php echo $group_key; ?>">Photo Collection</div> -->

			<?php if($group_key !== false): ?>
				<div class="group-contact in_con_w_opt_it" data-key="<?php echo $group_key; ?>">Group Message</div>
			<?php endif; ?>
			<?php  if($interest_activity['user_id'] == $_SESSION['id']): ?>
			<div class="in_con_w_opt_it remove_activity">Remove This Post</div>
			<?php endif; ?>
		</div>
	</div>
	<?php endif;?>
	
	
	
	
	
	
	
	
	
</div>

