<div class="post-wrapper post" style="padding:0px;" data-key="<?php echo $hash ?>">
	<div style="padding:16px 14px 0px 14px;"><a href="<?php echo $user_page_redirect; ?>"><img src="<?php echo $post_owner_pic; ?>" class="post-owner-picture hover-user-profile"   data-key="<?php echo $unique_iden; ?>"></a>
	<a class="plain-lk hover-user-profile" href="<?php echo $user_page_redirect; ?>" data-key="<?php echo $unique_iden; ?>"><span class="profile-name pointer post-user-name"><?php echo htmlentities($fullname) ?></span></a>
	<?php  if($interest_activity['user_id'] == $_SESSION['id']): ?>
		<img src="<?php echo IMGDIR ?>down_arrow_icon.png" class="trigger-pop toggle-operation pointer hdn">
	<?php endif; ?>
	<div style="margin-left: 10px; color: #969696;"><?php echo $post_time ?></div>
	</div>
	<div class="content">
		<div style="padding:0px 18px;">
		<div class="post-text">
			<div class="visible-post-scope">
				<div class="visible-content limit-height">
					<span><?php  echo htmlentities($description); ?></span>
				</div>
			</div>
		</div>
		<div class="moment-date">
			<?php echo $date ?>
		</div>
		</div>
		<div style="margin-top:10px;">
			<?php if($moment_photo !== false && isMediaDisplayable($photo_url)): ?>
			<img class="previewable" style="width:100%;" src="<?php echo U_IMGDIR.$photo_url ?>"  data-key="<?php echo $photo_hash ?>" data-sourceFrom = "m">
			<?php if($caption !== false && $caption !== null && !empty($caption)):?>
			<div style="text-align:right;margin-right:10px;"><span title="<?php echo htmlentities($caption); ?>" style="opacity:0.6;font-size:13px"><?php echo ((strlen($caption)>30)?substr($caption,0,30).'...':$caption) ?><span></div>
			<?php endif;?>
			<?php endif; ?>
		</div>
		
		<div class="post-inner-padding">
				<div class="inline-blk toggle-comment pointer" style="vertical-align:bottom"><img class="post-operation-icon pointer" src="<?php echo IMGDIR ?>ci.png"  title="Comment" height="16" width="16" ><div class="inline-blk cmt-num" style="margin:-3px 8px 0px 0px"><?php echo $comment_number; ?></div></div>
				<div class="inline-blk" style="vertical-align:bottom"><img class="post-operation-icon pointer <?php echo ($favored)?'undo-favor-activity':'favor-activity' ?>" src="<?php echo IMGDIR ?>favor_icon.png"  title="<?php echo ($favored)?'Undo Favor':'Favor' ?>" height="18" width="18"><div class="inline-blk favor-num <?php echo ($favor_number > 0)?' toggle-activity-favor plain-lk pointer':'' ?>" style="margin-top:0px;"><?php echo $favor_number; ?></div></div>
		</div>	
			<div class="favor-list list hdn">
				<div class="favor-list-inner list-inner">
				</div>
			</div>
			
			
			<div class="post-inner-padding regular-comment-wrapper comment-block hdn" style="padding-top:0px">
				<textarea class="fcy-txt comment-txt" style="margin-top:12px;" data-key="<?php echo $hash ?>"></textarea>
				<div class="comment-container" style="margin-top:20px;">
				
				</div>
			</div>
		
		
		
	</div>
	
	<?php  if($interest_activity['user_id'] == $_SESSION['id']): ?>

	<div class="in_con_opt_w popover hdn" style="top:38px;right:5px;">
		<div class="in_con_opt_w_inner" style="position:relative;width:100%;">
			<div class="arrow-up" style="position:absolute;top:-12px;right:1px;border-bottom:10px solid #FFFFFF"></div>
		
			<?php  if($interest_activity['user_id'] == $_SESSION['id']): ?>
				<div class="in_con_w_opt_it remove_activity">Remove This Moment</div>
			<?php  endif;?>
		</div>
	</div>
	
	<?php endif;?>
</div>
		