<div id="privacy-body">
	<div id="pravacy-header">
		<h2 class="title">Higout Privacy Policies</h2>
		<div>Higout is a website that allows you to share your moments, events, and photos about your interests. In order to connect people with similar interests together, we collect data and information provided by users to improve the suggestion and experience.</div>
	</div>
	<div>
		<h3 style="font-size:18px;margin-top:40px">Information and Data Collection and Use</h3>
		<ul>
			<li>
				<div class="sub-header">Account Information</div>
				In order to sign up an account on Higout, we collect personal information such as first name, last name, password and email address. Your first name and last name are public to all other users on Higout. Other users are able to search your name via the search engine within Higout. Your password is aim to be kept in private and known only to the user herself or himself. Your email address is the identification for signing in, receiving email notification, and is kept in private by default. However, other users are able to search, invite and engage other activities if they know your email address. 
			</li>
		
			<li>
				<div class="sub-header">Posts and Media Contents </div>
				Higout provides a platform for people to share what they are passionate about, including moments, events and other media contents. All the posts and media contents are public by default, in which case, other users are able to browse your posts and other contents that you distributed. 
			</li>
		
			<li>
				<div  class="sub-header">Cookies </div>
				Cookies are used for collecting additional data for improving services on Higout. They are generated when you interact with the website. Both session cookies and persistent cookies are collected and might be used and analyzed for improving user experience on Higout. 
			</li>
		
			<li>
				<div class="sub-header">Legal Request and Investigation </div>
					In order to provide a safe environment for every users in Higout communities, we would provide necessary data for legal requests and investigations. 
			</li>
		</u>
	</div>
	<div style="color:#888888;font-size:14px;margin-top:30px;">Effective since Oct 24, 2015.</div>
</div>