<div class="media-asset">
	<div class="preview-image-wrapper" ><img  src="" class="preview-image hdn" /></div>
</div>
<div class="media-detail">
	<div class="media-detial-container" style="padding:20px;">
		<div class="inline-blk user-avator">
		<a class="dummy-lk" href="<?php echo $user_page_redirect ?>"><img  class="hover-user-profile" data-key="<?php echo $unique_iden; ?>" style=" width: 100%;" src="<?php echo $profile_pic ?>"></a></div>
		<a class="dummy-lk" href="<?php echo $user_page_redirect ?>"><div class="profile-name pointer post-user-name inline-blk hover-user-profile" data-key="<?php echo $unique_iden; ?>"><?php echo htmlentities($fullname) ?></div></a>
		<div class="inline-blk pst-tm"><?php echo $post_time ?></div>
		<div>Just changed my profile picture</div>
	</div>
</div>