<div class="media-asset">
	<div class="preview-image-wrapper" style="width:100%;height:100%;overflow:hidden;"><img  src="" class="preview-image hdn" style="display:block;margin:0px auto;" /></div>
</div>
<div class="media-detail" style="text-align:left;background:#fff;min-height:100px;border-radius:0px 0px 6px 6px;">
	<div class="media-detial-container" style="padding:20px;margin-left:60px;">
		<img  style="height: 44px; width: 44px;float:left;margin:0px 14px 14px 0px; border-radius: 6px;margin-left:-60px;" src="<?php echo $profile_pic ?>">
		<div class="profile-name pointer post-user-name inline-blk"><?php echo htmlentities($fullname) ?></div>
		<div class="inline-blk" style="  margin-left: 10px;  color: #969696;"><?php echo $post_time ?></div>
		<div>Just changed my profile picture</div>
	</div>
</div>