<div class="reply-wrapper comment cmt" data-key="<?php echo $hash; ?>">
	<a href="<?php echo $user_page_redirect ?>"><img src="<?php  echo $post_owner_pic ?>" class="comment-from-picture hover-user-profile" data-key="<?php echo $unique_iden ?>"></a>
	<div class="inner">
		<div class="inner-container">
			<div class="visible-post-scope">
				<div class="visible-content limit-height">
				<a  href="<?php echo $user_page_redirect ?>" class="profile-name plain-lk normal-font hover-user-profile" data-key="<?php echo $unique_iden ?>"><?php echo htmlentities($fullname); ?>:</a>
				<span><?php echo htmlentities($text) ?></span>
				</div>
			</div>
			<div style="position:relative;top:2px;left:-2px">
				<div class="inline-blk"><span class="react"><?php echo $post_time ?></span></div>
				<?php if($user_id != $_SESSION['id']): ?>
					<div class="inline-blk"><span class="reply-comment react pointer">Reply</span></div>
				<?php endif; ?>
				<div class="inline-blk popover-throwable">
					<img  src="<?php echo IMGDIR ?>thumb_icon.png"   class="thumb reply-thumb <?php echo ($favored)?'undo-favor-reply':'favor-reply' ?>" height="16" width="16"><div class="inline-blk action-num reply-favor-num<?php echo ($favor_number < 1)?' hdn':'' ?>" style="position: relative; top: 1px;"><?php echo $favor_number; ?></div>			
				</div>
				<?php if($user_id == $_SESSION['id'] || $post_owner_id == $_SESSION['id']): ?>
					<img src="<?php echo IMGDIR ?>trashcan_icon.png" class="react pointer trashcan trash-reply hdn"  height="16" width="16" title="delete this comment">
				<?php  endif; ?>
			</div>
		</div>
		<?php if($user_id != $_SESSION['id']): ?>
			<textarea class="fcy-txt sub-reply hdn" style="margin-top:12px;" data-key="<?php echo $hash; ?>" placeholder="Reply to <?php echo $fullname ?>..."></textarea>
		<?php  endif;?>
	</div>
</div>

