<?php if($rows !== false): ?>
	<div class="inline-blk" style="width: 46%;margin-left:6px;">
			<?php echo $left_content; ?>
		</div>

	<div class="inline-blk" style="width: 46%;margin-left:8px;">
		<?php echo $right_content; ?>
	</div>
<?php else: ?>
		<div style="margin-left:14px;">No match result found <a href="<?php echo SEARCH_SIMILAR_PEOPLE_PATH; ?>&t=post" class="plain-lk red-act" >Search moments matched your interests?</a></div>
<?php  endif;?>