<div id="stream-suggest-block" >
	<div style="margin: 30px 10px 10px 4px;font-size: 16px;font-weight: 600;">Find Friends</div>
	<div class="user-profile-wrapper inline-blk" style="width: 100%;">
		<div class="user-profile operation-triggeable" style="width:100%;position:relative" data-key="c4a8afa33c5f2249106dd1e7">
		<div class="cover-wrapper">
							<img style="width:100%;" src="http://localhost:8888/media_u/597394f9fe626bbb1f13c37f/8211d78875aafbe92e59a98d/thumb_347d5436b433f27f3dbab721.jpg">
										<img src="http://localhost:8888/media/menu_navi_icon.png" style="float:none;width:20px;height:14px;position: absolute; right: 12px; top: 12px;" class="trigger-pop toggle-operation pointer hdn">
					</div>
	<div class="avator-inner-bottom" style="z-index:2;position:relative">
	<div class="avator-picture-wrapper" style="margin-top:-40px;margin-left:14px;">
		<div class="inline-blk" style="box-shadow:1px 1px 3px #848484;margin-right:10px;width:74px;height:74px;overflow:hidden;border-radius:4px;">
			<a href="http://localhost:8888/user/kesong.xie.1"><img class="profile-pic" style="width: 100%; min-height: 100%; transform: scale(1);" src="http://localhost:8888/media_u/597394f9fe626bbb1f13c37f/0d6f90406fc0cec43ad047ed/thumb_3409a8d2bf0f0a7a681d5071.jpg"></a>
		</div>
		<div class="inline-blk fullname" style="margin:0px 0px -4px 0px;vertical-align:bottom;font-size: 15px;color: #323232;font-weight: bold;">Nicholas Tse</div>
		<div class="summary" style="margin-top:10px;&quot;&quot;">
							<div style="font-size:13px;" class="txt_ofl">
					Borough of Manhattan Community College				</div>
							<div style="font-size:13px;" class="txt_ofl">
											Interested in Coding and Tennis									</div>
			
		</div>
	</div>
	
	</div>

<div class="in_con_opt_w fri-oper popover hdn" style="top:37px;right:7px;height:130px;width:66%;"> <!---don't forget to add popover after you've done-->
	<div class="in_con_opt_w_inner" style="position:relative;width:100%;height:100%;">
		<div class="arrow-up" style="position:absolute;top:-12px;right:5px;border-bottom:10px solid #FFFFFF"></div>
		<div class="inner-w" style="height:100%;position:relative;overflow:hidden;width:100%">
			<div class="main" style="position:absolute;width:100%;left:0px;background:#fff;">
				<div class="in_con_w_opt_it add-interest-group" style="cursor:default">Interest Group<img src="http://localhost:8888/media/right_nxt.png" style="float:right;margin-top:4px" height="12" width="12"></div>
				<div class="in_con_w_opt_it view-connection">Connections<img src="http://localhost:8888/media/right_nxt.png" style="float:right;margin-top:4px" height="12" width="12"></div>
				<div class="in_con_w_opt_it individual-contact">Message</div>
			</div>
			
			<!--starts int-group-->
			<div class="sub int-group child-scrollable hdn">
				<div class="back-to-main"><img class="prev" src="http://localhost:8888/media/left_nxt.png" height="12" width="12">Interest Group</div>
				<div style="max-height:130px;overflow:scroll">
																							<div class="in_con_border_top" data-key="55" data-hash="d5bd84657e85dfd9a7b118b2" title="In your Tennis interest group">
								<img class="label-image" src="http://localhost:8888/media_u/06f1e47fbdb03e48203ebfba/a6fec7cdeb815c80f86db1e6/thumb_b5502a3dc81be220e4c13cc2.jpeg">
								<div class="inline-blk txt_ofl red-act" style="width:95px;margin-top:3px;font-size:13px;">Tennis</div>
								<img class="remove-from-interest pointer animate-opacity" src="http://localhost:8888/media/minus_icon.png" title="Remove from interest group" height="16" wdith="16" style="float:right;margin-top:8px;">
							</div>
																																<div class="in_con_w_opt_it in_con_border_top selectable" title="Connect to my Programming interest group" data-key="58">
								<!--ends first sent if-->
								<img class="label-image" src="http://localhost:8888/media_u/06f1e47fbdb03e48203ebfba/8e7d76f8cbdca960ec12987a/thumb_f8c23cc82ee6c13fa3b23dad.png">
								<div class="inline-blk txt_ofl" style="width:95px;margin-top:3px;font-size:13px;">Programming</div>
							<!--ends second sent if-->
								</div>
																																<div class="in_con_border_top" data-key="67">
								<!--ends first sent if-->
								<img class="label-image" src="http://localhost:8888/media_u/06f1e47fbdb03e48203ebfba/15d2474cad6dd5764d810578/thumb_489903e32fe4ad83b5c6b5c5.jpg">
								<div class="inline-blk txt_ofl" style="width:95px;margin-top:3px;font-size:13px;">Guitar</div>
															<img src="http://localhost:8888/media/plane_sent_icon.png" class="request-sent" title="Request Sent">
							<!--ends second sent if-->
								</div>
																				</div> <!--ends max-height -->

				<div class="right-align" style="border-top:1px solid #f0f0f0;padding:8px 6px 6px 6px;">
					<div class="inline-blk action-button center-align request un-requestable">Request</div>
				</div>
			</div> <!-- ends int-group-->
			
			<!--starts collection group-->
			<div class="sub connection-group child-scrollable hdn">
				<div class="back-to-main"><img class="prev" src="http://localhost:8888/media/left_nxt.png" height="12" width="12">Connections</div>
				<div style="max-height:130px;overflow:scroll">
		
			
 				 				</div>
				</div>
				
			</div><!--ends collection group-->
		
			
			
			
			
		</div><!--ends inner-w-->
	</div><!--ends in_con_opt_w_inner -->
<!--ends in_con_opt_w -->
</div>
	</div>
</div>				
