<div class="reply-wrapper comment cmt" data-key="<?php echo $hash; ?>">
	<a href="<?php echo $user_page_redirect ?>"><img src="<?php  echo $post_owner_pic ?>" class="comment-from-picture hover-user-profile" data-key="<?php echo $unique_iden; ?>"></a>
	<div class="inner">
		<div class="inner-container">
			<div class="visible-post-scope">
				<div class="visible-content limit-height">
				<a class="profile-name plain-lk normal-font hover-user-profile" data-key="<?php echo $unique_iden; ?>" href="<?php echo $user_page_redirect ?>" ><?php echo htmlentities($fullname); ?>:</a>
				<span><?php echo htmlentities($text) ?></span>
				<div class="inline-blk"><a href="<?php echo $sub_user_page_redirect ?>" class="plain-lk profile-name pointer hover-user-profile" data-key="<?php echo $unique_iden_sub; ?>" style="font-size: 12px;
  font-weight: normal;">@<?php echo $at_fullname ?></a></div>
				</div>
			</div>
			<div style="position:relative;top:2px;left:-2px">
				<span class="react"><?php echo $post_time ?></span>
				<?php if($user_id != $_SESSION['id']): ?>
					<span class="reply-comment react pointer">Reply</span>
				<?php endif; ?>
				<img src="<?php echo IMGDIR ?>thumb_icon.png" class="thumb" title="like" height="16" width="16"> <span></span>
				<?php if($user_id == $_SESSION['id'] || $post_owner_id == $_SESSION['id']): ?>
					<img src="<?php echo IMGDIR ?>trashcan_icon.png" class="react pointer trashcan trash-reply hdn"  height="16" width="16" title="delete this comment">
				<?php  endif; ?>
			</div>
		</div>
		<?php if($user_id != $_SESSION['id']): ?>
			<textarea class="fcy-txt sub-reply hdn" style="margin-top:10px;" data-key="<?php echo $hash; ?>" placeholder="Reply to <?php echo $fullname ?>..."></textarea>
		<?php  endif;?>
	</div>
</div>

