<div id="terms-body">
	<div id="terms-header">
		<h2 class="title">Higout Term of Use</h2>
		<div>Higout is a website that allows you to share your moments, events, and photos about your interests. In order to connect people with similar interests together, we collect data and information provided by users to improve the suggestion and experience.</div>
	</div>
	<div>
		<ul>
			<li>
				<div class="sub-header">Membership</div>
				Higout is eligible for all individuals who is at least 18 years old. You acknowledge that you are at least 18 years old by signing up on Higout.
			</li>
		
			<li>
				<div class="sub-header">Contents</div>
				You are responsible for all the contents you share on HIgout, including text, and media contents.  All the contents you posted are public by default, and you are able to control their visible scopes through settings if applicable. You can not post content that violates the laws either from United States or other countries. By signing up on Higout, you grant us non-assignable, royalty-free, and non-exclusive license, worldwide license to use any content you post while using Higout services. You also agree that Higout has the rights to remove, distribute and use your contents, such as legal investigation, jurisdiction. 			</li>
		
			<li>
				<div  class="sub-header">Account </div>
				By signing up on Higout, you provide your first name, last name, email address, and password. You acknowledge that you are the only individual who uses the account to share contents on Higout. You should not share you password and other sensitive information pertinent to your account for any given reason. You agree that Higout is not responsible for the lost of the content if your account is accessed by the other third party. 
			</li>
		
			<li>
				<div class="sub-header">Copyright </div>
				Higout respects all user’s intellectual properties and we expect all the user should do the same. You should not share, distribute contents that violate other people’s intellectual properties for any given reason. You agree Higout has the right to remove any content that we deem to be violating the copyrights of other individuals and parties.	
			</li>
			
			<li>
				<div class="sub-header">Personal Safety</div>
				Higout provides a platform for users to connect with people with similar interests in their surroundings. You understand your posts, either event or moments,  are public by default, and we encourage users should not expose the exact location, contact information that might be involving personal safety. You should be responsible for your own personal properties. 
			</li>
		</u>
	</div>
	<div style="color:#888888;font-size:14px;margin-top:30px;">Effective since Oct 24, 2015.</div>
</div>