<?php if($upcoming_event_num > 0): ?>
<div class="interest-content-right inline-blk" style="width: 48%;margin-left:6px;">
		<?php echo $left_content; ?>
	</div>

<div class="interest-content-right inline-blk" style="width: 48%;margin-left:8px;">
	<?php echo $right_content; ?>
</div>
<?php else: ?>
	
	<div style="background:#fff; padding:20px;">
		<?php if($user_id != $_SESSION['id']): ?> 
		<?php
			echo $firstname.' has no upcoming event';
		?>
		<span href="" class="plain-lk pointer" style="color:#062AA3">Know what <?php echo $heOrShe ?> would like join?</span>
		<?php else: ?>
			You have no upcoming event
			<span href="" class="plain-lk pointer" style="color:#062AA3">Find event match my interest</span>

		<?php  endif;?>
	</div>
<?php endif; ?>


