<div class="user-profile operation-triggeable" style="width:100%;position:relative" data-key="<?php echo $hash ?>">
		<div class="cover-wrapper">
			<?php if($cover_pic !== false): ?>
				<img  style="width:100%;" src="<?php echo $cover_pic ?>">
			<?php endif; ?>
			<?php if($user_id != $_SESSION['id']): ?>
				<img src="<?php echo IMGDIR ?>menu_navi_icon.png" style="float:none;width:20px;height:14px;position: absolute; right: 12px; top: 12px;"class="trigger-pop hdn toggle-operation pointer">
			<?php endif; ?>
		</div>
	<div class="avator-inner-bottom" style="z-index:2;position:relative">
	<div class="avator-picture-wrapper" style="margin-top:-40px;margin-left:14px;" >
		<div class="inline-blk" style="box-shadow:1px 1px 3px #848484;margin-right:10px;width:74px;height:74px;overflow:hidden">
			<a href="<?php echo $user_page_redirect; ?>"><img  class="profile-pic" style="width:100%;min-height:100%;" src="<?php echo $profile_pic ?>"></a>
		</div>
		<div class="inline-blk fullname" style="margin:0px 0px -4px 0px;vertical-align:bottom;font-size: 15px;color: #323232;font-weight: bold;"><?php echo htmlentities($fullname); ?></div>
		<div class="summary" style=margin-top:10px;"">
			<?php if($education !== false): ?>
				<div style="font-size:13px;" class="txt_ofl">
					<?php 
						if($education !== false){
							if($education['school_name'] !== false){
								echo $education['school_name'];
							}else if($education['study'] !== false){
								echo $education['study'];
							}
						}
					 ?>
				</div>
			<?php endif;?>
				<div style="font-size:13px;" class="txt_ofl">
					<?php if($interest_list != ''): ?>
						Interested in <?php echo htmlentities($interest_list) ?>
					<?php endif; ?>
				</div>
			
		</div>
	</div>
	
	</div>
	
	
	
	
	
</div>
					