<!DOCTYPE>
<html>
	<body>
		<div style="padding:8px;">
			<div style="margin-top:30px;">
				<div>
					<div >
					<div style="margin-bottom:20px;">
						<div style="font: 300 14px/18px 'Lucida Grande',Lucida Sans,Lucida Sans Unicode,sans-serif,Arial,Helvetica,Verdana,sans-serif;color: #333;">Dear <?php echo $firstname.' '.$lastname ?>,</div>
					</div>

					<div style="margin-bottom:20px;">
						<div style="font: 300 14px/18px 'Lucida Grande',Lucida Sans,Lucida Sans Unicode,sans-serif,Arial,Helvetica,Verdana,sans-serif; color: #333;">Thank you for joining Higout.</div>
					</div>

					<div style="margin-bottom:10px;">
						<div style="font: 300 14px/18px 'Lucida Grande',Lucida Sans,Lucida Sans Unicode,sans-serif,Arial,Helvetica,Verdana,sans-serif; color: #333;line-height:2.0;">You recently signed up on Higout using the email account <a style="color:#000;font-weight:600;"><?php echo $email; ?></a>. To verify this email address, please click the link below and then you can sign in using this email adress and your password.</div>
					</div>

					<div style="margin-bottom:30px;">
						<a href="<?php echo ROOTDIR.'activate.php?register_id='.$register_id.'&code='.$code; ?>" style="font: 300 14px/18px 'Lucida Grande',Lucida Sans,Lucida Sans Unicode,sans-serif,Arial,Helvetica,Verdana,sans-serif; color: #333;color:rgb(60, 169, 226);text-decoration:none;">Verify now ></a>
					</div>

					<div>
						<div style="font: 300 14px/18px 'Lucida Grande',Lucida Sans,Lucida Sans Unicode,sans-serif,Arial,Helvetica,Verdana,sans-serif;line-height:2.0;">Best,<br>Higout Team </div>
					</div>

					</div>
				</div>
			</div>
		</div>
	</body>
</html>